// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const listGlobalActivity = `-- name: ListGlobalActivity :many

SELECT a.id, a.group_id, a.actor_id, a.type, a.entity_type, a.entity_id, a.payload, a.created_at
FROM activity_events a
WHERE a.group_id IN (SELECT group_id FROM group_members WHERE user_id = $1)
ORDER BY a.created_at DESC, a.id DESC
LIMIT $2
`

type ListGlobalActivityParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

// Activity domain queries for sqlc with pgx/v5.
// These replace manual Pool.Query/Exec calls in internal/activity/handlers.go
// Handler usage: Handler{Pool *pgxpool.Pool, Queries *db.Queries} where Queries wraps the pool.
func (q *Queries) ListGlobalActivity(ctx context.Context, arg ListGlobalActivityParams) ([]ActivityEvent, error) {
	rows, err := q.db.Query(ctx, listGlobalActivity, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityEvent
	for rows.Next() {
		var i ActivityEvent
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.ActorID,
			&i.Type,
			&i.EntityType,
			&i.EntityID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGlobalActivityWithCursor = `-- name: ListGlobalActivityWithCursor :many
SELECT a.id, a.group_id, a.actor_id, a.type, a.entity_type, a.entity_id, a.payload, a.created_at
FROM activity_events a
WHERE a.group_id IN (SELECT group_id FROM group_members WHERE user_id = $1)
  AND (a.created_at, a.id) < (SELECT cursor.created_at, cursor.id FROM activity_events cursor WHERE cursor.id = $2)
ORDER BY a.created_at DESC, a.id DESC
LIMIT $3
`

type ListGlobalActivityWithCursorParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) ListGlobalActivityWithCursor(ctx context.Context, arg ListGlobalActivityWithCursorParams) ([]ActivityEvent, error) {
	rows, err := q.db.Query(ctx, listGlobalActivityWithCursor, arg.UserID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityEvent
	for rows.Next() {
		var i ActivityEvent
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.ActorID,
			&i.Type,
			&i.EntityType,
			&i.EntityID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
