// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkAttachmentGroupMember = `-- name: CheckAttachmentGroupMember :one
SELECT EXISTS (SELECT 1 FROM group_members WHERE group_id = $1 AND user_id = $2) AS is_member
`

type CheckAttachmentGroupMemberParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) CheckAttachmentGroupMember(ctx context.Context, arg CheckAttachmentGroupMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkAttachmentGroupMember, arg.GroupID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const createAttachment = `-- name: CreateAttachment :exec
INSERT INTO expense_attachments (id, expense_id, user_id, file_url, file_name, mime_type, size_bytes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateAttachmentParams struct {
	ID        uuid.UUID `json:"id"`
	ExpenseID uuid.UUID `json:"expense_id"`
	UserID    uuid.UUID `json:"user_id"`
	FileUrl   string    `json:"file_url"`
	FileName  string    `json:"file_name"`
	MimeType  string    `json:"mime_type"`
	SizeBytes int32     `json:"size_bytes"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) error {
	_, err := q.db.Exec(ctx, createAttachment,
		arg.ID,
		arg.ExpenseID,
		arg.UserID,
		arg.FileUrl,
		arg.FileName,
		arg.MimeType,
		arg.SizeBytes,
	)
	return err
}

const deleteAttachment = `-- name: DeleteAttachment :exec
DELETE FROM expense_attachments WHERE id = $1
`

func (q *Queries) DeleteAttachment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAttachment, id)
	return err
}

const getAttachmentForServe = `-- name: GetAttachmentForServe :one
SELECT e.group_id, a.file_url, a.mime_type
FROM expense_attachments a
JOIN expenses e ON e.id = a.expense_id
WHERE a.id = $1 AND e.deleted_at IS NULL
`

type GetAttachmentForServeRow struct {
	GroupID  uuid.UUID `json:"group_id"`
	FileUrl  string    `json:"file_url"`
	MimeType string    `json:"mime_type"`
}

func (q *Queries) GetAttachmentForServe(ctx context.Context, id uuid.UUID) (GetAttachmentForServeRow, error) {
	row := q.db.QueryRow(ctx, getAttachmentForServe, id)
	var i GetAttachmentForServeRow
	err := row.Scan(&i.GroupID, &i.FileUrl, &i.MimeType)
	return i, err
}

const getAttachmentOwner = `-- name: GetAttachmentOwner :one
SELECT user_id, file_url FROM expense_attachments WHERE id = $1
`

type GetAttachmentOwnerRow struct {
	UserID  uuid.UUID `json:"user_id"`
	FileUrl string    `json:"file_url"`
}

func (q *Queries) GetAttachmentOwner(ctx context.Context, id uuid.UUID) (GetAttachmentOwnerRow, error) {
	row := q.db.QueryRow(ctx, getAttachmentOwner, id)
	var i GetAttachmentOwnerRow
	err := row.Scan(&i.UserID, &i.FileUrl)
	return i, err
}

const getExpenseGroupIDForAttachments = `-- name: GetExpenseGroupIDForAttachments :one

SELECT group_id FROM expenses WHERE id = $1 AND deleted_at IS NULL
`

// Attachments domain queries for sqlc with pgx/v5.
// These replace manual Pool.Query/Exec calls in internal/attachments/handlers.go
// Handler usage: Handler{Pool *pgxpool.Pool, Queries *db.Queries} where Queries wraps the pool.
func (q *Queries) GetExpenseGroupIDForAttachments(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getExpenseGroupIDForAttachments, id)
	var group_id uuid.UUID
	err := row.Scan(&group_id)
	return group_id, err
}

const listAttachments = `-- name: ListAttachments :many
SELECT id, user_id, file_url, file_name, mime_type, size_bytes, created_at
FROM expense_attachments
WHERE expense_id = $1
ORDER BY created_at DESC
`

type ListAttachmentsRow struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	FileUrl   string             `json:"file_url"`
	FileName  string             `json:"file_name"`
	MimeType  string             `json:"mime_type"`
	SizeBytes int32              `json:"size_bytes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAttachments(ctx context.Context, expenseID uuid.UUID) ([]ListAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, listAttachments, expenseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAttachmentsRow
	for rows.Next() {
		var i ListAttachmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FileUrl,
			&i.FileName,
			&i.MimeType,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
