// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailVerificationToken = `-- name: CreateEmailVerificationToken :exec
INSERT INTO email_verification_tokens (user_id, token_hash, expires_at) VALUES ($1, $2, now() + interval '24 hours')
`

type CreateEmailVerificationTokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
}

func (q *Queries) CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, createEmailVerificationToken, arg.UserID, arg.TokenHash)
	return err
}

const createOAuthIdentity = `-- name: CreateOAuthIdentity :exec
INSERT INTO oauth_identities (provider, subject, user_id) VALUES ('google', $1, $2)
`

type CreateOAuthIdentityParams struct {
	Subject string    `json:"subject"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateOAuthIdentity(ctx context.Context, arg CreateOAuthIdentityParams) error {
	_, err := q.db.Exec(ctx, createOAuthIdentity, arg.Subject, arg.UserID)
	return err
}

const createOAuthUser = `-- name: CreateOAuthUser :exec
INSERT INTO users (id, name, email, password_hash, email_verified_at) VALUES ($1, $2, $3, NULL, now())
`

type CreateOAuthUserParams struct {
	ID    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	Email string    `json:"email"`
}

func (q *Queries) CreateOAuthUser(ctx context.Context, arg CreateOAuthUserParams) error {
	_, err := q.db.Exec(ctx, createOAuthUser, arg.ID, arg.Name, arg.Email)
	return err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :exec
INSERT INTO password_reset_tokens (user_id, token_hash, expires_at) VALUES ($1, $2, now() + interval '1 hour')
`

type CreatePasswordResetTokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, createPasswordResetToken, arg.UserID, arg.TokenHash)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (user_id, refresh_token_hash, user_agent, ip, expires_at) VALUES ($1, $2, $3, $4, $5)
`

type CreateSessionParams struct {
	UserID           uuid.UUID          `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	UserAgent        pgtype.Text        `json:"user_agent"`
	Ip               pgtype.Text        `json:"ip"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.UserAgent,
		arg.Ip,
		arg.ExpiresAt,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, name, email, password_hash) VALUES ($1, $2, $3, $4)
`

type CreateUserParams struct {
	ID           uuid.UUID   `json:"id"`
	Name         string      `json:"name"`
	Email        string      `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
	)
	return err
}

const getEmailVerificationTokenUser = `-- name: GetEmailVerificationTokenUser :one
SELECT user_id FROM email_verification_tokens WHERE token_hash = $1 AND expires_at > now() AND verified_at IS NULL LIMIT 1
`

func (q *Queries) GetEmailVerificationTokenUser(ctx context.Context, tokenHash string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationTokenUser, tokenHash)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getOAuthIdentityForUpdate = `-- name: GetOAuthIdentityForUpdate :one
SELECT u.id, u.name, u.email FROM oauth_identities oi JOIN users u ON u.id = oi.user_id WHERE oi.provider = 'google' AND oi.subject = $1 FOR UPDATE
`

type GetOAuthIdentityForUpdateRow struct {
	ID    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	Email string    `json:"email"`
}

func (q *Queries) GetOAuthIdentityForUpdate(ctx context.Context, subject string) (GetOAuthIdentityForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getOAuthIdentityForUpdate, subject)
	var i GetOAuthIdentityForUpdateRow
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const getPasswordResetTokenUser = `-- name: GetPasswordResetTokenUser :one
SELECT user_id FROM password_reset_tokens WHERE token_hash = $1 AND expires_at > now() AND used_at IS NULL LIMIT 1
`

func (q *Queries) GetPasswordResetTokenUser(ctx context.Context, tokenHash string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getPasswordResetTokenUser, tokenHash)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getSessionUserByHash = `-- name: GetSessionUserByHash :one
SELECT user_id FROM sessions WHERE refresh_token_hash = $1 LIMIT 1
`

func (q *Queries) GetSessionUserByHash(ctx context.Context, refreshTokenHash string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getSessionUserByHash, refreshTokenHash)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getUserByEmail = `-- name: GetUserByEmail :one

SELECT id, name, email FROM users WHERE lower(email) = lower($1) LIMIT 1
`

type GetUserByEmailRow struct {
	ID    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	Email string    `json:"email"`
}

// Auth domain queries for sqlc with pgx/v5.
// These replace manual Pool.Query/Exec calls in internal/auth/handlers.go and internal/auth/auth.go
// Handler usage: Handler{Svc *auth.Service, Queries *db.Queries} or Service{Pool *pgxpool.Pool, Queries *db.Queries}
func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i GetUserByEmailRow
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const getUserByEmailForLogin = `-- name: GetUserByEmailForLogin :one
SELECT id, name, email, password_hash, email_verified_at FROM users WHERE lower(email) = lower($1) LIMIT 1
`

type GetUserByEmailForLoginRow struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	Email           string             `json:"email"`
	PasswordHash    pgtype.Text        `json:"password_hash"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
}

func (q *Queries) GetUserByEmailForLogin(ctx context.Context, lower string) (GetUserByEmailForLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmailForLogin, lower)
	var i GetUserByEmailForLoginRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const getUserByEmailForUpdate = `-- name: GetUserByEmailForUpdate :one
SELECT id, name, email FROM users WHERE lower(email) = lower($1) LIMIT 1 FOR UPDATE
`

type GetUserByEmailForUpdateRow struct {
	ID    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	Email string    `json:"email"`
}

func (q *Queries) GetUserByEmailForUpdate(ctx context.Context, lower string) (GetUserByEmailForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmailForUpdate, lower)
	var i GetUserByEmailForUpdateRow
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email FROM users WHERE id = $1 LIMIT 1
`

type GetUserByIDRow struct {
	ID    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	Email string    `json:"email"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const getUserIDByEmail = `-- name: GetUserIDByEmail :one
SELECT id FROM users WHERE lower(email) = lower($1) LIMIT 1
`

func (q *Queries) GetUserIDByEmail(ctx context.Context, lower string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUserIDByEmail, lower)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserVerificationByEmail = `-- name: GetUserVerificationByEmail :one
SELECT email, email_verified_at FROM users WHERE lower(email) = lower($1) LIMIT 1
`

type GetUserVerificationByEmailRow struct {
	Email           string             `json:"email"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
}

func (q *Queries) GetUserVerificationByEmail(ctx context.Context, lower string) (GetUserVerificationByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserVerificationByEmail, lower)
	var i GetUserVerificationByEmailRow
	err := row.Scan(&i.Email, &i.EmailVerifiedAt)
	return i, err
}

const getUserVerificationByID = `-- name: GetUserVerificationByID :one
SELECT email, email_verified_at FROM users WHERE id = $1 LIMIT 1
`

type GetUserVerificationByIDRow struct {
	Email           string             `json:"email"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
}

func (q *Queries) GetUserVerificationByID(ctx context.Context, id uuid.UUID) (GetUserVerificationByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserVerificationByID, id)
	var i GetUserVerificationByIDRow
	err := row.Scan(&i.Email, &i.EmailVerifiedAt)
	return i, err
}

const listSessionsByUser = `-- name: ListSessionsByUser :many
SELECT id, user_agent, ip, created_at, last_used_at, expires_at, revoked_at FROM sessions WHERE user_id = $1 ORDER BY created_at DESC
`

type ListSessionsByUserRow struct {
	ID         uuid.UUID          `json:"id"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	Ip         pgtype.Text        `json:"ip"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) ListSessionsByUser(ctx context.Context, userID uuid.UUID) ([]ListSessionsByUserRow, error) {
	rows, err := q.db.Query(ctx, listSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsByUserRow
	for rows.Next() {
		var i ListSessionsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserAgent,
			&i.Ip,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailVerificationVerified = `-- name: MarkEmailVerificationVerified :exec
UPDATE email_verification_tokens SET verified_at = now() WHERE token_hash = $1
`

func (q *Queries) MarkEmailVerificationVerified(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, markEmailVerificationVerified, tokenHash)
	return err
}

const markPasswordResetUsed = `-- name: MarkPasswordResetUsed :exec
UPDATE password_reset_tokens SET used_at = now() WHERE token_hash = $1
`

func (q *Queries) MarkPasswordResetUsed(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, markPasswordResetUsed, tokenHash)
	return err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE sessions SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeSessionByHash = `-- name: RevokeSessionByHash :exec
UPDATE sessions SET revoked_at = now() WHERE refresh_token_hash = $1
`

func (q *Queries) RevokeSessionByHash(ctx context.Context, refreshTokenHash string) error {
	_, err := q.db.Exec(ctx, revokeSessionByHash, refreshTokenHash)
	return err
}

const revokeSessionByID = `-- name: RevokeSessionByID :exec
UPDATE sessions SET revoked_at = now() WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeSessionByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RevokeSessionByID(ctx context.Context, arg RevokeSessionByIDParams) error {
	_, err := q.db.Exec(ctx, revokeSessionByID, arg.ID, arg.UserID)
	return err
}

const revokeSessionByIDReturning = `-- name: RevokeSessionByIDReturning :one
UPDATE sessions SET revoked_at = now() WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL RETURNING id
`

type RevokeSessionByIDReturningParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RevokeSessionByIDReturning(ctx context.Context, arg RevokeSessionByIDReturningParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, revokeSessionByIDReturning, arg.ID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const rotateSession = `-- name: RotateSession :one
WITH rotated AS (
    UPDATE sessions SET revoked_at = now() WHERE sessions.refresh_token_hash = $1 AND sessions.revoked_at IS NULL RETURNING sessions.user_id, sessions.id
)
INSERT INTO sessions (user_id, refresh_token_hash, expires_at, rotated_from)
SELECT rotated.user_id, $2, now() + interval '30 days', rotated.id FROM rotated
RETURNING id
`

type RotateSessionParams struct {
	RefreshTokenHash   string `json:"refresh_token_hash"`
	RefreshTokenHash_2 string `json:"refresh_token_hash_2"`
}

func (q *Queries) RotateSession(ctx context.Context, arg RotateSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, rotateSession, arg.RefreshTokenHash, arg.RefreshTokenHash_2)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const setEmailVerified = `-- name: SetEmailVerified :exec
UPDATE users SET email_verified_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) SetEmailVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setEmailVerified, id)
	return err
}

const setUserEmailVerifiedIfNull = `-- name: SetUserEmailVerifiedIfNull :exec
UPDATE users SET email_verified_at = COALESCE(email_verified_at, now()), updated_at = now() WHERE id = $1
`

func (q *Queries) SetUserEmailVerifiedIfNull(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setUserEmailVerifiedIfNull, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $1, updated_at = now() WHERE id = $2
`

type UpdateUserPasswordParams struct {
	PasswordHash pgtype.Text `json:"password_hash"`
	ID           uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}
