// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: balances.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getMyGroupBalances = `-- name: GetMyGroupBalances :many
SELECT g.id, g.name, g.currency,
       COALESCE(paid.total, 0)::bigint - COALESCE(owed.total, 0)::bigint + COALESCE(recv.total, 0)::bigint - COALESCE(sent.total, 0)::bigint AS balance
FROM groups g
JOIN group_members gm ON gm.group_id = g.id AND gm.user_id = $1
LEFT JOIN (
    SELECT group_id, paid_by, SUM(ROUND(amount * COALESCE(exchange_rate, 1))::bigint)::bigint AS total
    FROM expenses WHERE deleted_at IS NULL GROUP BY group_id, paid_by
) paid ON paid.group_id = g.id AND paid.paid_by = $1
LEFT JOIN (
    SELECT e.group_id, s.user_id, SUM(ROUND(s.amount * COALESCE(e.exchange_rate, 1))::bigint)::bigint AS total
    FROM expense_splits s JOIN expenses e ON e.id = s.expense_id
    WHERE e.deleted_at IS NULL GROUP BY e.group_id, s.user_id
) owed ON owed.group_id = g.id AND owed.user_id = $1
LEFT JOIN (
    SELECT group_id, from_user AS user_id, SUM(amount)::bigint AS total FROM settlements WHERE deleted_at IS NULL GROUP BY group_id, from_user
) recv ON recv.group_id = g.id AND recv.user_id = $1
LEFT JOIN (
    SELECT group_id, to_user AS user_id, SUM(amount)::bigint AS total FROM settlements WHERE deleted_at IS NULL GROUP BY group_id, to_user
) sent ON sent.group_id = g.id AND sent.user_id = $1
WHERE g.archived_at IS NULL
`

type GetMyGroupBalancesRow struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Currency string    `json:"currency"`
	Balance  int32     `json:"balance"`
}

func (q *Queries) GetMyGroupBalances(ctx context.Context, userID uuid.UUID) ([]GetMyGroupBalancesRow, error) {
	rows, err := q.db.Query(ctx, getMyGroupBalances, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMyGroupBalancesRow
	for rows.Next() {
		var i GetMyGroupBalancesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Currency,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserDefaultCurrency = `-- name: GetUserDefaultCurrency :one

SELECT default_currency FROM users WHERE id = $1
`

// Balances domain queries for sqlc with pgx/v5.
// These replace manual Pool.Query/Exec calls in internal/balances/handlers.go
// Handler usage: Handler{Pool *pgxpool.Pool, Queries *db.Queries} where Queries wraps the pool.
func (q *Queries) GetUserDefaultCurrency(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserDefaultCurrency, id)
	var default_currency string
	err := row.Scan(&default_currency)
	return default_currency, err
}

const listGroupMemberIDs = `-- name: ListGroupMemberIDs :many
SELECT user_id FROM group_members WHERE group_id = $1
`

func (q *Queries) ListGroupMemberIDs(ctx context.Context, groupID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listGroupMemberIDs, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettlementsByGroup = `-- name: ListSettlementsByGroup :many
SELECT from_user, to_user, amount FROM settlements WHERE group_id = $1 AND deleted_at IS NULL
`

type ListSettlementsByGroupRow struct {
	FromUser uuid.UUID `json:"from_user"`
	ToUser   uuid.UUID `json:"to_user"`
	Amount   int64     `json:"amount"`
}

func (q *Queries) ListSettlementsByGroup(ctx context.Context, groupID uuid.UUID) ([]ListSettlementsByGroupRow, error) {
	rows, err := q.db.Query(ctx, listSettlementsByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSettlementsByGroupRow
	for rows.Next() {
		var i ListSettlementsByGroupRow
		if err := rows.Scan(&i.FromUser, &i.ToUser, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumOwedByGroup = `-- name: SumOwedByGroup :many
SELECT s.user_id, SUM(ROUND(s.amount * COALESCE(e.exchange_rate, 1))::bigint)::bigint AS total
FROM expense_splits s
JOIN expenses e ON e.id = s.expense_id
WHERE e.group_id = $1 AND e.deleted_at IS NULL
GROUP BY s.user_id
`

type SumOwedByGroupRow struct {
	UserID uuid.UUID `json:"user_id"`
	Total  int64     `json:"total"`
}

func (q *Queries) SumOwedByGroup(ctx context.Context, groupID uuid.UUID) ([]SumOwedByGroupRow, error) {
	rows, err := q.db.Query(ctx, sumOwedByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumOwedByGroupRow
	for rows.Next() {
		var i SumOwedByGroupRow
		if err := rows.Scan(&i.UserID, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumPaidByGroup = `-- name: SumPaidByGroup :many
SELECT paid_by AS user_id, SUM(ROUND(amount * COALESCE(exchange_rate, 1))::bigint)::bigint AS total
FROM expenses
WHERE group_id = $1 AND deleted_at IS NULL
GROUP BY paid_by
`

type SumPaidByGroupRow struct {
	UserID uuid.UUID `json:"user_id"`
	Total  int64     `json:"total"`
}

func (q *Queries) SumPaidByGroup(ctx context.Context, groupID uuid.UUID) ([]SumPaidByGroupRow, error) {
	rows, err := q.db.Query(ctx, sumPaidByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumPaidByGroupRow
	for rows.Next() {
		var i SumPaidByGroupRow
		if err := rows.Scan(&i.UserID, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
