// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :exec
INSERT INTO categories (id, name, icon, color, grouping, is_system, owner_id)
VALUES ($1, $2, $3, $4, $5, false, $6)
`

type CreateCategoryParams struct {
	ID       uuid.UUID   `json:"id"`
	Name     string      `json:"name"`
	Icon     string      `json:"icon"`
	Color    string      `json:"color"`
	Grouping pgtype.Text `json:"grouping"`
	OwnerID  uuid.UUID   `json:"owner_id"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) error {
	_, err := q.db.Exec(ctx, createCategory,
		arg.ID,
		arg.Name,
		arg.Icon,
		arg.Color,
		arg.Grouping,
		arg.OwnerID,
	)
	return err
}

const listCategories = `-- name: ListCategories :many

SELECT id, name, icon, color, is_system, coalesce(grouping, 'Uncategorized') AS grouping
FROM categories
WHERE is_system = true OR owner_id = $1
ORDER BY grouping, is_system DESC, name
`

type ListCategoriesRow struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Icon     string    `json:"icon"`
	Color    string    `json:"color"`
	IsSystem bool      `json:"is_system"`
	Grouping string    `json:"grouping"`
}

// Categories domain queries for sqlc with pgx/v5.
// These replace manual Pool.Query/Exec calls in internal/categories/handlers.go
// Handler usage: Handler{Pool *pgxpool.Pool, Queries *db.Queries} where Queries wraps the pool.
func (q *Queries) ListCategories(ctx context.Context, ownerID uuid.UUID) ([]ListCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listCategories, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoriesRow
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Color,
			&i.IsSystem,
			&i.Grouping,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
