// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :exec
INSERT INTO expense_comments (id, expense_id, user_id, body) VALUES ($1, $2, $3, $4)
`

type CreateCommentParams struct {
	ID        uuid.UUID `json:"id"`
	ExpenseID uuid.UUID `json:"expense_id"`
	UserID    uuid.UUID `json:"user_id"`
	Body      string    `json:"body"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) error {
	_, err := q.db.Exec(ctx, createComment,
		arg.ID,
		arg.ExpenseID,
		arg.UserID,
		arg.Body,
	)
	return err
}

const createCommentActivity = `-- name: CreateCommentActivity :exec
INSERT INTO activity_events (group_id, actor_id, type, entity_type, entity_id, payload)
VALUES ($1, $2, 'COMMENT_ADDED', 'comment', $3, $4)
`

type CreateCommentActivityParams struct {
	GroupID  uuid.UUID `json:"group_id"`
	ActorID  uuid.UUID `json:"actor_id"`
	EntityID uuid.UUID `json:"entity_id"`
	Payload  []byte    `json:"payload"`
}

func (q *Queries) CreateCommentActivity(ctx context.Context, arg CreateCommentActivityParams) error {
	_, err := q.db.Exec(ctx, createCommentActivity,
		arg.GroupID,
		arg.ActorID,
		arg.EntityID,
		arg.Payload,
	)
	return err
}

const createMentionNotification = `-- name: CreateMentionNotification :exec
INSERT INTO notifications (user_id, type, title, body, data) VALUES ($1, 'MENTION', $2, $3, $4)
`

type CreateMentionNotificationParams struct {
	UserID uuid.UUID `json:"user_id"`
	Title  string    `json:"title"`
	Body   string    `json:"body"`
	Data   []byte    `json:"data"`
}

func (q *Queries) CreateMentionNotification(ctx context.Context, arg CreateMentionNotificationParams) error {
	_, err := q.db.Exec(ctx, createMentionNotification,
		arg.UserID,
		arg.Title,
		arg.Body,
		arg.Data,
	)
	return err
}

const getCommentOwner = `-- name: GetCommentOwner :one
SELECT user_id FROM expense_comments WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCommentOwner(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getCommentOwner, id)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getExpenseGroupIDForComments = `-- name: GetExpenseGroupIDForComments :one

SELECT group_id FROM expenses WHERE id = $1 AND deleted_at IS NULL
`

// Comments domain queries for sqlc with pgx/v5.
// These replace manual Pool.Query/Exec calls in internal/comments/handlers.go
// Handler usage: Handler{Pool *pgxpool.Pool, Queries *db.Queries} where Queries wraps the pool.
func (q *Queries) GetExpenseGroupIDForComments(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getExpenseGroupIDForComments, id)
	var group_id uuid.UUID
	err := row.Scan(&group_id)
	return group_id, err
}

const listCommentNotifyUsers = `-- name: ListCommentNotifyUsers :many
SELECT DISTINCT s.user_id FROM expense_splits s WHERE s.expense_id = $1 AND s.user_id != $2
`

type ListCommentNotifyUsersParams struct {
	ExpenseID uuid.UUID `json:"expense_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) ListCommentNotifyUsers(ctx context.Context, arg ListCommentNotifyUsersParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listCommentNotifyUsers, arg.ExpenseID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComments = `-- name: ListComments :many
SELECT c.id, c.user_id, u.name, coalesce(u.avatar_url, '') AS avatar_url, c.body, c.created_at
FROM expense_comments c
JOIN users u ON u.id = c.user_id
WHERE c.expense_id = $1 AND c.deleted_at IS NULL
ORDER BY c.created_at ASC
`

type ListCommentsRow struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Name      string             `json:"name"`
	AvatarUrl string             `json:"avatar_url"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListComments(ctx context.Context, expenseID uuid.UUID) ([]ListCommentsRow, error) {
	rows, err := q.db.Query(ctx, listComments, expenseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsRow
	for rows.Next() {
		var i ListCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.AvatarUrl,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteComment = `-- name: SoftDeleteComment :exec
UPDATE expense_comments SET deleted_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteComment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteComment, id)
	return err
}
