// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expenses.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkIsGroupMember = `-- name: CheckIsGroupMember :one
SELECT EXISTS(SELECT 1 FROM group_members WHERE group_id = $1 AND user_id = $2) AS is_member
`

type CheckIsGroupMemberParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) CheckIsGroupMember(ctx context.Context, arg CheckIsGroupMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkIsGroupMember, arg.GroupID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const countExpensesByGroup = `-- name: CountExpensesByGroup :one
SELECT COUNT(*) FROM expenses WHERE group_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountExpensesByGroup(ctx context.Context, groupID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countExpensesByGroup, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExpense = `-- name: CreateExpense :exec
INSERT INTO expenses (id, group_id, description, amount, currency, split_mode, paid_by, category_id, notes, expense_date, created_by, exchange_rate, base_currency, base_amount)
VALUES ($1, $2, $3, $4, $5, $6, $7, NULLIF($8::uuid, '00000000-0000-0000-0000-000000000000'::uuid), $9, $10, $11, $12, $13, $14)
`

type CreateExpenseParams struct {
	ID           uuid.UUID      `json:"id"`
	GroupID      uuid.UUID      `json:"group_id"`
	Description  string         `json:"description"`
	Amount       int64          `json:"amount"`
	Currency     string         `json:"currency"`
	SplitMode    string         `json:"split_mode"`
	PaidBy       uuid.UUID      `json:"paid_by"`
	Column8      pgtype.UUID    `json:"column_8"`
	Notes        string         `json:"notes"`
	ExpenseDate  pgtype.Date    `json:"expense_date"`
	CreatedBy    uuid.UUID      `json:"created_by"`
	ExchangeRate pgtype.Numeric `json:"exchange_rate"`
	BaseCurrency pgtype.Text    `json:"base_currency"`
	BaseAmount   pgtype.Int8    `json:"base_amount"`
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) error {
	_, err := q.db.Exec(ctx, createExpense,
		arg.ID,
		arg.GroupID,
		arg.Description,
		arg.Amount,
		arg.Currency,
		arg.SplitMode,
		arg.PaidBy,
		arg.Column8,
		arg.Notes,
		arg.ExpenseDate,
		arg.CreatedBy,
		arg.ExchangeRate,
		arg.BaseCurrency,
		arg.BaseAmount,
	)
	return err
}

const createNotificationExpenseAdded = `-- name: CreateNotificationExpenseAdded :exec
INSERT INTO notifications (user_id, type, title, body, data) VALUES ($1, 'EXPENSE_ADDED', $2, $3, $4)
`

type CreateNotificationExpenseAddedParams struct {
	UserID uuid.UUID `json:"user_id"`
	Title  string    `json:"title"`
	Body   string    `json:"body"`
	Data   []byte    `json:"data"`
}

func (q *Queries) CreateNotificationExpenseAdded(ctx context.Context, arg CreateNotificationExpenseAddedParams) error {
	_, err := q.db.Exec(ctx, createNotificationExpenseAdded,
		arg.UserID,
		arg.Title,
		arg.Body,
		arg.Data,
	)
	return err
}

const deleteExpenseSplits = `-- name: DeleteExpenseSplits :exec
DELETE FROM expense_splits WHERE expense_id = $1
`

func (q *Queries) DeleteExpenseSplits(ctx context.Context, expenseID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteExpenseSplits, expenseID)
	return err
}

const getExpense = `-- name: GetExpense :one
SELECT group_id, description, amount, currency, split_mode, paid_by, category_id, notes, expense_date, created_by, deleted_at FROM expenses WHERE id = $1
`

type GetExpenseRow struct {
	GroupID     uuid.UUID          `json:"group_id"`
	Description string             `json:"description"`
	Amount      int64              `json:"amount"`
	Currency    string             `json:"currency"`
	SplitMode   string             `json:"split_mode"`
	PaidBy      uuid.UUID          `json:"paid_by"`
	CategoryID  uuid.UUID          `json:"category_id"`
	Notes       string             `json:"notes"`
	ExpenseDate pgtype.Date        `json:"expense_date"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetExpense(ctx context.Context, id uuid.UUID) (GetExpenseRow, error) {
	row := q.db.QueryRow(ctx, getExpense, id)
	var i GetExpenseRow
	err := row.Scan(
		&i.GroupID,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.SplitMode,
		&i.PaidBy,
		&i.CategoryID,
		&i.Notes,
		&i.ExpenseDate,
		&i.CreatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const getExpenseDetails = `-- name: GetExpenseDetails :one
SELECT id, group_id, description, amount, currency, split_mode, paid_by, category_id, notes, expense_date, created_by, created_at, updated_at, deleted_at, exchange_rate, base_currency, base_amount FROM expenses WHERE id = $1
`

type GetExpenseDetailsRow struct {
	ID           uuid.UUID          `json:"id"`
	GroupID      uuid.UUID          `json:"group_id"`
	Description  string             `json:"description"`
	Amount       int64              `json:"amount"`
	Currency     string             `json:"currency"`
	SplitMode    string             `json:"split_mode"`
	PaidBy       uuid.UUID          `json:"paid_by"`
	CategoryID   uuid.UUID          `json:"category_id"`
	Notes        string             `json:"notes"`
	ExpenseDate  pgtype.Date        `json:"expense_date"`
	CreatedBy    uuid.UUID          `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	ExchangeRate pgtype.Numeric     `json:"exchange_rate"`
	BaseCurrency pgtype.Text        `json:"base_currency"`
	BaseAmount   pgtype.Int8        `json:"base_amount"`
}

func (q *Queries) GetExpenseDetails(ctx context.Context, id uuid.UUID) (GetExpenseDetailsRow, error) {
	row := q.db.QueryRow(ctx, getExpenseDetails, id)
	var i GetExpenseDetailsRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.SplitMode,
		&i.PaidBy,
		&i.CategoryID,
		&i.Notes,
		&i.ExpenseDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ExchangeRate,
		&i.BaseCurrency,
		&i.BaseAmount,
	)
	return i, err
}

const getExpenseForDelete = `-- name: GetExpenseForDelete :one
SELECT group_id, created_by FROM expenses WHERE id = $1 AND deleted_at IS NULL
`

type GetExpenseForDeleteRow struct {
	GroupID   uuid.UUID `json:"group_id"`
	CreatedBy uuid.UUID `json:"created_by"`
}

func (q *Queries) GetExpenseForDelete(ctx context.Context, id uuid.UUID) (GetExpenseForDeleteRow, error) {
	row := q.db.QueryRow(ctx, getExpenseForDelete, id)
	var i GetExpenseForDeleteRow
	err := row.Scan(&i.GroupID, &i.CreatedBy)
	return i, err
}

const getExpenseForUpdate = `-- name: GetExpenseForUpdate :one
SELECT group_id, created_by, deleted_at FROM expenses WHERE id = $1
`

type GetExpenseForUpdateRow struct {
	GroupID   uuid.UUID          `json:"group_id"`
	CreatedBy uuid.UUID          `json:"created_by"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetExpenseForUpdate(ctx context.Context, id uuid.UUID) (GetExpenseForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getExpenseForUpdate, id)
	var i GetExpenseForUpdateRow
	err := row.Scan(&i.GroupID, &i.CreatedBy, &i.DeletedAt)
	return i, err
}

const getExpenseMemberRole = `-- name: GetExpenseMemberRole :one
SELECT role FROM group_members WHERE group_id = $1 AND user_id = $2
`

type GetExpenseMemberRoleParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) GetExpenseMemberRole(ctx context.Context, arg GetExpenseMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getExpenseMemberRole, arg.GroupID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getGroupCurrency = `-- name: GetGroupCurrency :one

SELECT currency FROM groups WHERE id = $1
`

// Expenses domain queries for sqlc with pgx/v5.
// These replace manual Pool.Query/Exec calls in internal/expenses/handlers.go
// Handler usage: Handler{Pool *pgxpool.Pool, Queries *db.Queries} where Queries wraps the pool.
func (q *Queries) GetGroupCurrency(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getGroupCurrency, id)
	var currency string
	err := row.Scan(&currency)
	return currency, err
}

const insertExpenseActivityAdded = `-- name: InsertExpenseActivityAdded :exec
INSERT INTO activity_events (group_id, actor_id, type, entity_type, entity_id, payload) VALUES ($1, $2, 'EXPENSE_ADDED', 'expense', $3, $4)
`

type InsertExpenseActivityAddedParams struct {
	GroupID  uuid.UUID `json:"group_id"`
	ActorID  uuid.UUID `json:"actor_id"`
	EntityID uuid.UUID `json:"entity_id"`
	Payload  []byte    `json:"payload"`
}

func (q *Queries) InsertExpenseActivityAdded(ctx context.Context, arg InsertExpenseActivityAddedParams) error {
	_, err := q.db.Exec(ctx, insertExpenseActivityAdded,
		arg.GroupID,
		arg.ActorID,
		arg.EntityID,
		arg.Payload,
	)
	return err
}

const insertExpenseActivityDeleted = `-- name: InsertExpenseActivityDeleted :exec
INSERT INTO activity_events (group_id, actor_id, type, entity_type, entity_id, payload) VALUES ($1, $2, 'EXPENSE_DELETED', 'expense', $3, $4)
`

type InsertExpenseActivityDeletedParams struct {
	GroupID  uuid.UUID `json:"group_id"`
	ActorID  uuid.UUID `json:"actor_id"`
	EntityID uuid.UUID `json:"entity_id"`
	Payload  []byte    `json:"payload"`
}

func (q *Queries) InsertExpenseActivityDeleted(ctx context.Context, arg InsertExpenseActivityDeletedParams) error {
	_, err := q.db.Exec(ctx, insertExpenseActivityDeleted,
		arg.GroupID,
		arg.ActorID,
		arg.EntityID,
		arg.Payload,
	)
	return err
}

const insertExpenseActivityUpdated = `-- name: InsertExpenseActivityUpdated :exec
INSERT INTO activity_events (group_id, actor_id, type, entity_type, entity_id, payload) VALUES ($1, $2, 'EXPENSE_UPDATED', 'expense', $3, $4)
`

type InsertExpenseActivityUpdatedParams struct {
	GroupID  uuid.UUID `json:"group_id"`
	ActorID  uuid.UUID `json:"actor_id"`
	EntityID uuid.UUID `json:"entity_id"`
	Payload  []byte    `json:"payload"`
}

func (q *Queries) InsertExpenseActivityUpdated(ctx context.Context, arg InsertExpenseActivityUpdatedParams) error {
	_, err := q.db.Exec(ctx, insertExpenseActivityUpdated,
		arg.GroupID,
		arg.ActorID,
		arg.EntityID,
		arg.Payload,
	)
	return err
}

const insertExpenseSplit = `-- name: InsertExpenseSplit :exec
INSERT INTO expense_splits (expense_id, user_id, amount, percentage, shares) VALUES ($1, $2, $3, $4, $5)
`

type InsertExpenseSplitParams struct {
	ExpenseID  uuid.UUID      `json:"expense_id"`
	UserID     uuid.UUID      `json:"user_id"`
	Amount     int64          `json:"amount"`
	Percentage pgtype.Numeric `json:"percentage"`
	Shares     pgtype.Int4    `json:"shares"`
}

func (q *Queries) InsertExpenseSplit(ctx context.Context, arg InsertExpenseSplitParams) error {
	_, err := q.db.Exec(ctx, insertExpenseSplit,
		arg.ExpenseID,
		arg.UserID,
		arg.Amount,
		arg.Percentage,
		arg.Shares,
	)
	return err
}

const isExpenseMember = `-- name: IsExpenseMember :one
SELECT EXISTS(SELECT 1 FROM group_members WHERE group_id = $1 AND user_id = $2) AS is_member
`

type IsExpenseMemberParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) IsExpenseMember(ctx context.Context, arg IsExpenseMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isExpenseMember, arg.GroupID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const listExpenseSplits = `-- name: ListExpenseSplits :many
SELECT user_id, amount, percentage, shares FROM expense_splits WHERE expense_id = $1
`

type ListExpenseSplitsRow struct {
	UserID     uuid.UUID      `json:"user_id"`
	Amount     int64          `json:"amount"`
	Percentage pgtype.Numeric `json:"percentage"`
	Shares     pgtype.Int4    `json:"shares"`
}

func (q *Queries) ListExpenseSplits(ctx context.Context, expenseID uuid.UUID) ([]ListExpenseSplitsRow, error) {
	rows, err := q.db.Query(ctx, listExpenseSplits, expenseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpenseSplitsRow
	for rows.Next() {
		var i ListExpenseSplitsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Amount,
			&i.Percentage,
			&i.Shares,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenseSplitsByExpenseIDs = `-- name: ListExpenseSplitsByExpenseIDs :many
SELECT expense_id, user_id, amount, percentage, shares FROM expense_splits WHERE expense_id = ANY($1::uuid[])
`

type ListExpenseSplitsByExpenseIDsRow struct {
	ExpenseID  uuid.UUID      `json:"expense_id"`
	UserID     uuid.UUID      `json:"user_id"`
	Amount     int64          `json:"amount"`
	Percentage pgtype.Numeric `json:"percentage"`
	Shares     pgtype.Int4    `json:"shares"`
}

func (q *Queries) ListExpenseSplitsByExpenseIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListExpenseSplitsByExpenseIDsRow, error) {
	rows, err := q.db.Query(ctx, listExpenseSplitsByExpenseIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpenseSplitsByExpenseIDsRow
	for rows.Next() {
		var i ListExpenseSplitsByExpenseIDsRow
		if err := rows.Scan(
			&i.ExpenseID,
			&i.UserID,
			&i.Amount,
			&i.Percentage,
			&i.Shares,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenses = `-- name: ListExpenses :many
SELECT e.id, e.description, e.amount, e.currency, e.split_mode, e.paid_by, e.category_id, e.notes, e.expense_date, e.created_by, e.created_at, e.updated_at
FROM expenses e WHERE e.group_id = $1 AND e.deleted_at IS NULL ORDER BY e.created_at DESC, e.id DESC
`

type ListExpensesRow struct {
	ID          uuid.UUID          `json:"id"`
	Description string             `json:"description"`
	Amount      int64              `json:"amount"`
	Currency    string             `json:"currency"`
	SplitMode   string             `json:"split_mode"`
	PaidBy      uuid.UUID          `json:"paid_by"`
	CategoryID  uuid.UUID          `json:"category_id"`
	Notes       string             `json:"notes"`
	ExpenseDate pgtype.Date        `json:"expense_date"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListExpenses(ctx context.Context, groupID uuid.UUID) ([]ListExpensesRow, error) {
	rows, err := q.db.Query(ctx, listExpenses, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpensesRow
	for rows.Next() {
		var i ListExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.SplitMode,
			&i.PaidBy,
			&i.CategoryID,
			&i.Notes,
			&i.ExpenseDate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpensesByGroup = `-- name: ListExpensesByGroup :many
SELECT e.id, e.description, e.amount, e.currency, e.split_mode, e.paid_by, e.category_id, e.notes, e.expense_date, e.created_by, e.created_at, e.updated_at
FROM expenses e WHERE e.group_id = $1 AND e.deleted_at IS NULL ORDER BY e.created_at DESC, e.id DESC LIMIT $2
`

type ListExpensesByGroupParams struct {
	GroupID uuid.UUID `json:"group_id"`
	Limit   int32     `json:"limit"`
}

type ListExpensesByGroupRow struct {
	ID          uuid.UUID          `json:"id"`
	Description string             `json:"description"`
	Amount      int64              `json:"amount"`
	Currency    string             `json:"currency"`
	SplitMode   string             `json:"split_mode"`
	PaidBy      uuid.UUID          `json:"paid_by"`
	CategoryID  uuid.UUID          `json:"category_id"`
	Notes       string             `json:"notes"`
	ExpenseDate pgtype.Date        `json:"expense_date"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListExpensesByGroup(ctx context.Context, arg ListExpensesByGroupParams) ([]ListExpensesByGroupRow, error) {
	rows, err := q.db.Query(ctx, listExpensesByGroup, arg.GroupID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpensesByGroupRow
	for rows.Next() {
		var i ListExpensesByGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.SplitMode,
			&i.PaidBy,
			&i.CategoryID,
			&i.Notes,
			&i.ExpenseDate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpensesWithCursor = `-- name: ListExpensesWithCursor :many
SELECT e.id, e.description, e.amount, e.currency, e.split_mode, e.paid_by, e.category_id, e.notes, e.expense_date, e.created_by, e.created_at, e.updated_at
FROM expenses e WHERE e.group_id = $1 AND e.deleted_at IS NULL AND (e.created_at, e.id) < (SELECT ex.created_at, ex.id FROM expenses ex WHERE ex.id = $2) ORDER BY e.created_at DESC, e.id DESC LIMIT $3
`

type ListExpensesWithCursorParams struct {
	GroupID uuid.UUID `json:"group_id"`
	ID      uuid.UUID `json:"id"`
	Limit   int32     `json:"limit"`
}

type ListExpensesWithCursorRow struct {
	ID          uuid.UUID          `json:"id"`
	Description string             `json:"description"`
	Amount      int64              `json:"amount"`
	Currency    string             `json:"currency"`
	SplitMode   string             `json:"split_mode"`
	PaidBy      uuid.UUID          `json:"paid_by"`
	CategoryID  uuid.UUID          `json:"category_id"`
	Notes       string             `json:"notes"`
	ExpenseDate pgtype.Date        `json:"expense_date"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListExpensesWithCursor(ctx context.Context, arg ListExpensesWithCursorParams) ([]ListExpensesWithCursorRow, error) {
	rows, err := q.db.Query(ctx, listExpensesWithCursor, arg.GroupID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpensesWithCursorRow
	for rows.Next() {
		var i ListExpensesWithCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.SplitMode,
			&i.PaidBy,
			&i.CategoryID,
			&i.Notes,
			&i.ExpenseDate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOtherGroupMembers = `-- name: ListOtherGroupMembers :many
SELECT user_id FROM group_members WHERE group_id = $1 AND user_id != $2
`

type ListOtherGroupMembersParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) ListOtherGroupMembers(ctx context.Context, arg ListOtherGroupMembersParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listOtherGroupMembers, arg.GroupID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteExpense = `-- name: SoftDeleteExpense :exec
UPDATE expenses SET deleted_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteExpense(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteExpense, id)
	return err
}

const updateExpense = `-- name: UpdateExpense :exec
UPDATE expenses SET description = $1, amount = $2, currency = $3, split_mode = $4, paid_by = $5, category_id = NULLIF($6::uuid, '00000000-0000-0000-0000-000000000000'::uuid), notes = $7, expense_date = $8, exchange_rate = $9, base_currency = $10, base_amount = $11, updated_at = now() WHERE id = $12
`

type UpdateExpenseParams struct {
	Description  string         `json:"description"`
	Amount       int64          `json:"amount"`
	Currency     string         `json:"currency"`
	SplitMode    string         `json:"split_mode"`
	PaidBy       uuid.UUID      `json:"paid_by"`
	Column6      pgtype.UUID    `json:"column_6"`
	Notes        string         `json:"notes"`
	ExpenseDate  pgtype.Date    `json:"expense_date"`
	ExchangeRate pgtype.Numeric `json:"exchange_rate"`
	BaseCurrency pgtype.Text    `json:"base_currency"`
	BaseAmount   pgtype.Int8    `json:"base_amount"`
	ID           uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) error {
	_, err := q.db.Exec(ctx, updateExpense,
		arg.Description,
		arg.Amount,
		arg.Currency,
		arg.SplitMode,
		arg.PaidBy,
		arg.Column6,
		arg.Notes,
		arg.ExpenseDate,
		arg.ExchangeRate,
		arg.BaseCurrency,
		arg.BaseAmount,
		arg.ID,
	)
	return err
}
