// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: export.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkExportGroupMember = `-- name: CheckExportGroupMember :one
SELECT EXISTS(SELECT 1 FROM group_members WHERE group_id = $1 AND user_id = $2) AS is_member
`

type CheckExportGroupMemberParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) CheckExportGroupMember(ctx context.Context, arg CheckExportGroupMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkExportGroupMember, arg.GroupID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const exportGroupCSV = `-- name: ExportGroupCSV :many
SELECT e.expense_date, e.description, coalesce(c.name, '') AS category,
       pu.name AS paid_by, e.amount, e.currency, e.split_mode,
       su.name AS split_user, coalesce(s.amount, 0)::bigint AS split_amount
FROM expenses e
JOIN users pu ON pu.id = e.paid_by
LEFT JOIN categories c ON c.id = e.category_id
LEFT JOIN expense_splits s ON s.expense_id = e.id
LEFT JOIN users su ON su.id = s.user_id
WHERE e.group_id = $1 AND e.deleted_at IS NULL
ORDER BY e.expense_date, e.created_at
`

type ExportGroupCSVRow struct {
	ExpenseDate pgtype.Date `json:"expense_date"`
	Description string      `json:"description"`
	Category    string      `json:"category"`
	PaidBy      string      `json:"paid_by"`
	Amount      int64       `json:"amount"`
	Currency    string      `json:"currency"`
	SplitMode   string      `json:"split_mode"`
	SplitUser   pgtype.Text `json:"split_user"`
	SplitAmount int64       `json:"split_amount"`
}

func (q *Queries) ExportGroupCSV(ctx context.Context, groupID uuid.UUID) ([]ExportGroupCSVRow, error) {
	rows, err := q.db.Query(ctx, exportGroupCSV, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportGroupCSVRow
	for rows.Next() {
		var i ExportGroupCSVRow
		if err := rows.Scan(
			&i.ExpenseDate,
			&i.Description,
			&i.Category,
			&i.PaidBy,
			&i.Amount,
			&i.Currency,
			&i.SplitMode,
			&i.SplitUser,
			&i.SplitAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportGroupJSON = `-- name: ExportGroupJSON :many
SELECT e.id, e.description, coalesce(c.name, '') AS category, pu.name AS paid_by, e.amount, e.currency, e.split_mode, e.expense_date, e.created_at, e.notes
FROM expenses e
JOIN users pu ON pu.id = e.paid_by
LEFT JOIN categories c ON c.id = e.category_id
WHERE e.group_id = $1 AND e.deleted_at IS NULL
ORDER BY e.expense_date, e.created_at
`

type ExportGroupJSONRow struct {
	ID          uuid.UUID          `json:"id"`
	Description string             `json:"description"`
	Category    string             `json:"category"`
	PaidBy      string             `json:"paid_by"`
	Amount      int64              `json:"amount"`
	Currency    string             `json:"currency"`
	SplitMode   string             `json:"split_mode"`
	ExpenseDate pgtype.Date        `json:"expense_date"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Notes       string             `json:"notes"`
}

func (q *Queries) ExportGroupJSON(ctx context.Context, groupID uuid.UUID) ([]ExportGroupJSONRow, error) {
	rows, err := q.db.Query(ctx, exportGroupJSON, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportGroupJSONRow
	for rows.Next() {
		var i ExportGroupJSONRow
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Category,
			&i.PaidBy,
			&i.Amount,
			&i.Currency,
			&i.SplitMode,
			&i.ExpenseDate,
			&i.CreatedAt,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportGroupSettlements = `-- name: ExportGroupSettlements :many
SELECT st.settled_at, f.name AS from_name, t.name AS to_name, st.amount, st.currency, st.note
FROM settlements st
JOIN users f ON f.id = st.from_user
JOIN users t ON t.id = st.to_user
WHERE st.group_id = $1 AND st.deleted_at IS NULL
ORDER BY st.settled_at
`

type ExportGroupSettlementsRow struct {
	SettledAt pgtype.Timestamptz `json:"settled_at"`
	FromName  string             `json:"from_name"`
	ToName    string             `json:"to_name"`
	Amount    int64              `json:"amount"`
	Currency  string             `json:"currency"`
	Note      string             `json:"note"`
}

func (q *Queries) ExportGroupSettlements(ctx context.Context, groupID uuid.UUID) ([]ExportGroupSettlementsRow, error) {
	rows, err := q.db.Query(ctx, exportGroupSettlements, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportGroupSettlementsRow
	for rows.Next() {
		var i ExportGroupSettlementsRow
		if err := rows.Scan(
			&i.SettledAt,
			&i.FromName,
			&i.ToName,
			&i.Amount,
			&i.Currency,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportMyCSV = `-- name: ExportMyCSV :many

SELECT e.expense_date, g.name AS group_name, e.description, coalesce(c.name, '') AS category,
       pu.name AS paid_by, e.amount, e.currency, e.split_mode,
       su.name AS split_user, coalesce(s.amount, 0)::bigint AS split_amount
FROM expenses e
JOIN groups g ON g.id = e.group_id
JOIN group_members gm ON gm.group_id = e.group_id AND gm.user_id = $1
JOIN users pu ON pu.id = e.paid_by
LEFT JOIN categories c ON c.id = e.category_id
LEFT JOIN expense_splits s ON s.expense_id = e.id
LEFT JOIN users su ON su.id = s.user_id
WHERE e.deleted_at IS NULL
ORDER BY e.expense_date, e.created_at
`

type ExportMyCSVRow struct {
	ExpenseDate pgtype.Date `json:"expense_date"`
	GroupName   string      `json:"group_name"`
	Description string      `json:"description"`
	Category    string      `json:"category"`
	PaidBy      string      `json:"paid_by"`
	Amount      int64       `json:"amount"`
	Currency    string      `json:"currency"`
	SplitMode   string      `json:"split_mode"`
	SplitUser   pgtype.Text `json:"split_user"`
	SplitAmount int64       `json:"split_amount"`
}

// Export domain queries for sqlc with pgx/v5.
// These replace manual Pool.Query/Exec calls in internal/export/handlers.go
// Handler usage: Handler{Pool *pgxpool.Pool, Queries *db.Queries} where Queries wraps the pool.
func (q *Queries) ExportMyCSV(ctx context.Context, userID uuid.UUID) ([]ExportMyCSVRow, error) {
	rows, err := q.db.Query(ctx, exportMyCSV, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportMyCSVRow
	for rows.Next() {
		var i ExportMyCSVRow
		if err := rows.Scan(
			&i.ExpenseDate,
			&i.GroupName,
			&i.Description,
			&i.Category,
			&i.PaidBy,
			&i.Amount,
			&i.Currency,
			&i.SplitMode,
			&i.SplitUser,
			&i.SplitAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportMyJSON = `-- name: ExportMyJSON :many
SELECT e.id, e.group_id, g.name AS group_name, e.description, coalesce(c.name, '') AS category, pu.name AS paid_by, e.amount, e.currency, e.split_mode, e.expense_date, e.created_at
FROM expenses e
JOIN groups g ON g.id = e.group_id
JOIN group_members gm ON gm.group_id = e.group_id AND gm.user_id = $1
JOIN users pu ON pu.id = e.paid_by
LEFT JOIN categories c ON c.id = e.category_id
WHERE e.deleted_at IS NULL
ORDER BY e.expense_date, e.created_at
`

type ExportMyJSONRow struct {
	ID          uuid.UUID          `json:"id"`
	GroupID     uuid.UUID          `json:"group_id"`
	GroupName   string             `json:"group_name"`
	Description string             `json:"description"`
	Category    string             `json:"category"`
	PaidBy      string             `json:"paid_by"`
	Amount      int64              `json:"amount"`
	Currency    string             `json:"currency"`
	SplitMode   string             `json:"split_mode"`
	ExpenseDate pgtype.Date        `json:"expense_date"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ExportMyJSON(ctx context.Context, userID uuid.UUID) ([]ExportMyJSONRow, error) {
	rows, err := q.db.Query(ctx, exportMyJSON, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportMyJSONRow
	for rows.Next() {
		var i ExportMyJSONRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.GroupName,
			&i.Description,
			&i.Category,
			&i.PaidBy,
			&i.Amount,
			&i.Currency,
			&i.SplitMode,
			&i.ExpenseDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExportGroupName = `-- name: GetExportGroupName :one
SELECT name FROM groups WHERE id = $1
`

func (q *Queries) GetExportGroupName(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getExportGroupName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}
