// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: friends.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptFriendRequest = `-- name: AcceptFriendRequest :execrows
UPDATE friendships SET status = 'ACCEPTED', updated_at = now() WHERE user_id = $1 AND friend_id = $2 AND status = 'PENDING' AND action_by != $3
`

type AcceptFriendRequestParams struct {
	UserID   uuid.UUID   `json:"user_id"`
	FriendID uuid.UUID   `json:"friend_id"`
	ActionBy pgtype.UUID `json:"action_by"`
}

func (q *Queries) AcceptFriendRequest(ctx context.Context, arg AcceptFriendRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, acceptFriendRequest, arg.UserID, arg.FriendID, arg.ActionBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const acceptFriendRequestReturning = `-- name: AcceptFriendRequestReturning :one
UPDATE friendships SET status = 'ACCEPTED', updated_at = now() WHERE user_id = $1 AND friend_id = $2 AND status = 'PENDING' AND action_by != $3 RETURNING id
`

type AcceptFriendRequestReturningParams struct {
	UserID   uuid.UUID   `json:"user_id"`
	FriendID uuid.UUID   `json:"friend_id"`
	ActionBy pgtype.UUID `json:"action_by"`
}

func (q *Queries) AcceptFriendRequestReturning(ctx context.Context, arg AcceptFriendRequestReturningParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, acceptFriendRequestReturning, arg.UserID, arg.FriendID, arg.ActionBy)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const addDirectGroupMember = `-- name: AddDirectGroupMember :exec
INSERT INTO group_members (group_id, user_id, role) VALUES ($1, $2, 'OWNER') ON CONFLICT DO NOTHING
`

type AddDirectGroupMemberParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) AddDirectGroupMember(ctx context.Context, arg AddDirectGroupMemberParams) error {
	_, err := q.db.Exec(ctx, addDirectGroupMember, arg.GroupID, arg.UserID)
	return err
}

const blockUser = `-- name: BlockUser :exec
INSERT INTO friendships (id, user_id, friend_id, status, action_by) VALUES ($1, $2, $3, 'BLOCKED', $4)
`

type BlockUserParams struct {
	ID       uuid.UUID   `json:"id"`
	UserID   uuid.UUID   `json:"user_id"`
	FriendID uuid.UUID   `json:"friend_id"`
	ActionBy pgtype.UUID `json:"action_by"`
}

func (q *Queries) BlockUser(ctx context.Context, arg BlockUserParams) error {
	_, err := q.db.Exec(ctx, blockUser,
		arg.ID,
		arg.UserID,
		arg.FriendID,
		arg.ActionBy,
	)
	return err
}

const checkUserExistsNotAnonymous = `-- name: CheckUserExistsNotAnonymous :one
SELECT EXISTS(SELECT 1 FROM users WHERE id = $1 AND is_anonymous = false) AS exists
`

func (q *Queries) CheckUserExistsNotAnonymous(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserExistsNotAnonymous, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createDirectGroup = `-- name: CreateDirectGroup :exec
INSERT INTO groups (id, name, currency, group_type, direct_key, created_by) VALUES ($1, $2, 'NPR', 'DIRECT', $3, $4)
`

type CreateDirectGroupParams struct {
	ID        uuid.UUID   `json:"id"`
	Name      string      `json:"name"`
	DirectKey pgtype.Text `json:"direct_key"`
	CreatedBy uuid.UUID   `json:"created_by"`
}

func (q *Queries) CreateDirectGroup(ctx context.Context, arg CreateDirectGroupParams) error {
	_, err := q.db.Exec(ctx, createDirectGroup,
		arg.ID,
		arg.Name,
		arg.DirectKey,
		arg.CreatedBy,
	)
	return err
}

const createFriendInvite = `-- name: CreateFriendInvite :exec
INSERT INTO friend_invites (id, email, token_hash, invited_by) VALUES ($1, $2, $3, $4)
ON CONFLICT (lower(email), invited_by) WHERE status = 'PENDING'
DO UPDATE SET token_hash = $3, created_at = now(), expires_at = now() + interval '7 days'
`

type CreateFriendInviteParams struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	TokenHash string    `json:"token_hash"`
	InvitedBy uuid.UUID `json:"invited_by"`
}

func (q *Queries) CreateFriendInvite(ctx context.Context, arg CreateFriendInviteParams) error {
	_, err := q.db.Exec(ctx, createFriendInvite,
		arg.ID,
		arg.Email,
		arg.TokenHash,
		arg.InvitedBy,
	)
	return err
}

const createFriendRequestNotification = `-- name: CreateFriendRequestNotification :exec
INSERT INTO notifications (user_id, type, title, body, data) VALUES ($1, 'FRIEND_REQUEST', $2, $3, $4)
`

type CreateFriendRequestNotificationParams struct {
	UserID uuid.UUID `json:"user_id"`
	Title  string    `json:"title"`
	Body   string    `json:"body"`
	Data   []byte    `json:"data"`
}

func (q *Queries) CreateFriendRequestNotification(ctx context.Context, arg CreateFriendRequestNotificationParams) error {
	_, err := q.db.Exec(ctx, createFriendRequestNotification,
		arg.UserID,
		arg.Title,
		arg.Body,
		arg.Data,
	)
	return err
}

const deleteFriendship = `-- name: DeleteFriendship :execrows
DELETE FROM friendships WHERE user_id = $1 AND friend_id = $2
`

type DeleteFriendshipParams struct {
	UserID   uuid.UUID `json:"user_id"`
	FriendID uuid.UUID `json:"friend_id"`
}

func (q *Queries) DeleteFriendship(ctx context.Context, arg DeleteFriendshipParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFriendship, arg.UserID, arg.FriendID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDirectBalance = `-- name: GetDirectBalance :one
SELECT
    (COALESCE((SELECT SUM(ROUND(expenses.amount * COALESCE(expenses.exchange_rate, 1))::bigint) FROM expenses WHERE expenses.group_id = $1 AND expenses.paid_by = $2 AND expenses.deleted_at IS NULL), 0::bigint)
  - COALESCE((SELECT SUM(ROUND(s.amount * COALESCE(e.exchange_rate, 1))::bigint) FROM expense_splits s JOIN expenses e ON e.id = s.expense_id WHERE e.group_id = $1 AND s.user_id = $2 AND e.deleted_at IS NULL), 0::bigint)
  + COALESCE((SELECT SUM(settlements.amount) FROM settlements WHERE settlements.group_id = $1 AND settlements.from_user = $2 AND settlements.deleted_at IS NULL), 0::bigint)
  - COALESCE((SELECT SUM(settlements.amount) FROM settlements WHERE settlements.group_id = $1 AND settlements.to_user = $2 AND settlements.deleted_at IS NULL), 0::bigint))::bigint AS amount,
    (SELECT groups.currency FROM groups WHERE groups.id = $1)::text AS currency
`

type GetDirectBalanceParams struct {
	GroupID uuid.UUID `json:"group_id"`
	PaidBy  uuid.UUID `json:"paid_by"`
}

type GetDirectBalanceRow struct {
	Amount   int64  `json:"amount"`
	Currency string `json:"currency"`
}

func (q *Queries) GetDirectBalance(ctx context.Context, arg GetDirectBalanceParams) (GetDirectBalanceRow, error) {
	row := q.db.QueryRow(ctx, getDirectBalance, arg.GroupID, arg.PaidBy)
	var i GetDirectBalanceRow
	err := row.Scan(&i.Amount, &i.Currency)
	return i, err
}

const getDirectGroupByKey = `-- name: GetDirectGroupByKey :one
SELECT id FROM groups WHERE direct_key = $1
`

func (q *Queries) GetDirectGroupByKey(ctx context.Context, directKey pgtype.Text) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getDirectGroupByKey, directKey)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getFriendDirectLedgerBalance = `-- name: GetFriendDirectLedgerBalance :one
SELECT
    (COALESCE((SELECT SUM(ROUND(expenses.amount * COALESCE(expenses.exchange_rate, 1))::bigint) FROM expenses WHERE expenses.group_id = $1 AND expenses.paid_by = $2 AND expenses.deleted_at IS NULL), 0::bigint)
  - COALESCE((SELECT SUM(ROUND(s.amount * COALESCE(e.exchange_rate, 1))::bigint) FROM expense_splits s JOIN expenses e ON e.id = s.expense_id WHERE e.group_id = $1 AND s.user_id = $2 AND e.deleted_at IS NULL), 0::bigint)
  + COALESCE((SELECT SUM(settlements.amount) FROM settlements WHERE settlements.group_id = $1 AND settlements.from_user = $2 AND settlements.deleted_at IS NULL), 0::bigint)
  - COALESCE((SELECT SUM(settlements.amount) FROM settlements WHERE settlements.group_id = $1 AND settlements.to_user = $2 AND settlements.deleted_at IS NULL), 0::bigint))::bigint AS amount,
    (SELECT groups.currency FROM groups WHERE groups.id = $1)::text AS currency
`

type GetFriendDirectLedgerBalanceParams struct {
	GroupID uuid.UUID `json:"group_id"`
	PaidBy  uuid.UUID `json:"paid_by"`
}

type GetFriendDirectLedgerBalanceRow struct {
	Amount   int64  `json:"amount"`
	Currency string `json:"currency"`
}

func (q *Queries) GetFriendDirectLedgerBalance(ctx context.Context, arg GetFriendDirectLedgerBalanceParams) (GetFriendDirectLedgerBalanceRow, error) {
	row := q.db.QueryRow(ctx, getFriendDirectLedgerBalance, arg.GroupID, arg.PaidBy)
	var i GetFriendDirectLedgerBalanceRow
	err := row.Scan(&i.Amount, &i.Currency)
	return i, err
}

const getFriendInviteByToken = `-- name: GetFriendInviteByToken :one
SELECT id, email, invited_by, status, expires_at FROM friend_invites WHERE token_hash = $1
`

type GetFriendInviteByTokenRow struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	InvitedBy uuid.UUID          `json:"invited_by"`
	Status    string             `json:"status"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetFriendInviteByToken(ctx context.Context, tokenHash string) (GetFriendInviteByTokenRow, error) {
	row := q.db.QueryRow(ctx, getFriendInviteByToken, tokenHash)
	var i GetFriendInviteByTokenRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.InvitedBy,
		&i.Status,
		&i.ExpiresAt,
	)
	return i, err
}

const getFriendInviteByTokenForUpdate = `-- name: GetFriendInviteByTokenForUpdate :one
SELECT id, email, invited_by, status, expires_at FROM friend_invites WHERE token_hash = $1 FOR UPDATE
`

type GetFriendInviteByTokenForUpdateRow struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	InvitedBy uuid.UUID          `json:"invited_by"`
	Status    string             `json:"status"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetFriendInviteByTokenForUpdate(ctx context.Context, tokenHash string) (GetFriendInviteByTokenForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getFriendInviteByTokenForUpdate, tokenHash)
	var i GetFriendInviteByTokenForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.InvitedBy,
		&i.Status,
		&i.ExpiresAt,
	)
	return i, err
}

const getFriendUserByEmail = `-- name: GetFriendUserByEmail :one
SELECT id FROM users WHERE lower(email) = lower($1)
`

func (q *Queries) GetFriendUserByEmail(ctx context.Context, lower string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getFriendUserByEmail, lower)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getFriendUserIDByEmail = `-- name: GetFriendUserIDByEmail :one
SELECT id FROM users WHERE lower(email) = lower($1) LIMIT 1
`

func (q *Queries) GetFriendUserIDByEmail(ctx context.Context, lower string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getFriendUserIDByEmail, lower)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getFriendship = `-- name: GetFriendship :one
SELECT id, user_id, friend_id, status, action_by, created_at, updated_at FROM friendships WHERE user_id = $1 AND friend_id = $2
`

type GetFriendshipParams struct {
	UserID   uuid.UUID `json:"user_id"`
	FriendID uuid.UUID `json:"friend_id"`
}

func (q *Queries) GetFriendship(ctx context.Context, arg GetFriendshipParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, getFriendship, arg.UserID, arg.FriendID)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FriendID,
		&i.Status,
		&i.ActionBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFriendshipByUsers = `-- name: GetFriendshipByUsers :one
SELECT status FROM friendships WHERE user_id = $1 AND friend_id = $2
`

type GetFriendshipByUsersParams struct {
	UserID   uuid.UUID `json:"user_id"`
	FriendID uuid.UUID `json:"friend_id"`
}

func (q *Queries) GetFriendshipByUsers(ctx context.Context, arg GetFriendshipByUsersParams) (string, error) {
	row := q.db.QueryRow(ctx, getFriendshipByUsers, arg.UserID, arg.FriendID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const getFriendshipStatus = `-- name: GetFriendshipStatus :one

SELECT status FROM friendships WHERE user_id = $1 AND friend_id = $2
`

type GetFriendshipStatusParams struct {
	UserID   uuid.UUID `json:"user_id"`
	FriendID uuid.UUID `json:"friend_id"`
}

// Friends domain queries for sqlc with pgx/v5.
// These replace manual Pool.Query/Exec calls in internal/friends/handlers.go and internal/friends/direct.go
// Handler usage: Handler{Pool *pgxpool.Pool, Queries *db.Queries, Mailer *mailer.Mailer} where Queries wraps the pool.
// Transaction usage: qtx := h.Queries.WithTx(tx)
func (q *Queries) GetFriendshipStatus(ctx context.Context, arg GetFriendshipStatusParams) (string, error) {
	row := q.db.QueryRow(ctx, getFriendshipStatus, arg.UserID, arg.FriendID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const getUserAvatarByID = `-- name: GetUserAvatarByID :one
SELECT coalesce(avatar_url, '') AS avatar_url FROM users WHERE id = $1
`

func (q *Queries) GetUserAvatarByID(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserAvatarByID, id)
	var avatar_url string
	err := row.Scan(&avatar_url)
	return avatar_url, err
}

const getUserLowerEmailByID = `-- name: GetUserLowerEmailByID :one
SELECT lower(email) AS lower_email FROM users WHERE id = $1
`

func (q *Queries) GetUserLowerEmailByID(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserLowerEmailByID, id)
	var lower_email string
	err := row.Scan(&lower_email)
	return lower_email, err
}

const getUserNameByID = `-- name: GetUserNameByID :one
SELECT name FROM users WHERE id = $1
`

func (q *Queries) GetUserNameByID(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserNameByID, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const listFriendRequests = `-- name: ListFriendRequests :many
SELECT
    f.id AS friendship_id,
    f.action_by AS from_user,
    u.name,
    coalesce(u.avatar_url, '') AS avatar_url,
    f.created_at
FROM friendships f
JOIN users u ON u.id = f.action_by
WHERE (f.user_id = $1 OR f.friend_id = $1) AND f.status = 'PENDING' AND f.action_by != $1
ORDER BY f.created_at DESC
`

type ListFriendRequestsRow struct {
	FriendshipID uuid.UUID          `json:"friendship_id"`
	FromUser     pgtype.UUID        `json:"from_user"`
	Name         string             `json:"name"`
	AvatarUrl    string             `json:"avatar_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListFriendRequests(ctx context.Context, userID uuid.UUID) ([]ListFriendRequestsRow, error) {
	rows, err := q.db.Query(ctx, listFriendRequests, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFriendRequestsRow
	for rows.Next() {
		var i ListFriendRequestsRow
		if err := rows.Scan(
			&i.FriendshipID,
			&i.FromUser,
			&i.Name,
			&i.AvatarUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFriends = `-- name: ListFriends :many
SELECT
    f.id AS friendship_id,
    f.status,
    (CASE WHEN f.user_id = $1 THEN f.friend_id ELSE f.user_id END)::uuid AS other_id,
    u.name,
    coalesce(u.avatar_url, '') AS avatar_url
FROM friendships f
JOIN users u ON u.id = CASE WHEN f.user_id = $1 THEN f.friend_id ELSE f.user_id END
WHERE (f.user_id = $1 OR f.friend_id = $1) AND f.status = 'ACCEPTED'
`

type ListFriendsRow struct {
	FriendshipID uuid.UUID   `json:"friendship_id"`
	Status       string      `json:"status"`
	OtherID      pgtype.UUID `json:"other_id"`
	Name         string      `json:"name"`
	AvatarUrl    string      `json:"avatar_url"`
}

func (q *Queries) ListFriends(ctx context.Context, userID uuid.UUID) ([]ListFriendsRow, error) {
	rows, err := q.db.Query(ctx, listFriends, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFriendsRow
	for rows.Next() {
		var i ListFriendsRow
		if err := rows.Scan(
			&i.FriendshipID,
			&i.Status,
			&i.OtherID,
			&i.Name,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectFriendRequest = `-- name: RejectFriendRequest :execrows
DELETE FROM friendships WHERE user_id = $1 AND friend_id = $2 AND status = 'PENDING' AND action_by != $3
`

type RejectFriendRequestParams struct {
	UserID   uuid.UUID   `json:"user_id"`
	FriendID uuid.UUID   `json:"friend_id"`
	ActionBy pgtype.UUID `json:"action_by"`
}

func (q *Queries) RejectFriendRequest(ctx context.Context, arg RejectFriendRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, rejectFriendRequest, arg.UserID, arg.FriendID, arg.ActionBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sendFriendRequest = `-- name: SendFriendRequest :exec
INSERT INTO friendships (id, user_id, friend_id, status, action_by) VALUES ($1, $2, $3, 'PENDING', $4)
`

type SendFriendRequestParams struct {
	ID       uuid.UUID   `json:"id"`
	UserID   uuid.UUID   `json:"user_id"`
	FriendID uuid.UUID   `json:"friend_id"`
	ActionBy pgtype.UUID `json:"action_by"`
}

func (q *Queries) SendFriendRequest(ctx context.Context, arg SendFriendRequestParams) error {
	_, err := q.db.Exec(ctx, sendFriendRequest,
		arg.ID,
		arg.UserID,
		arg.FriendID,
		arg.ActionBy,
	)
	return err
}

const updateFriendInviteAccepted = `-- name: UpdateFriendInviteAccepted :exec
UPDATE friend_invites SET status = 'ACCEPTED' WHERE id = $1
`

func (q *Queries) UpdateFriendInviteAccepted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateFriendInviteAccepted, id)
	return err
}

const upsertFriendshipAccepted = `-- name: UpsertFriendshipAccepted :exec
INSERT INTO friendships (id, user_id, friend_id, status, action_by) VALUES ($1, $2, $3, 'ACCEPTED', $4)
ON CONFLICT (LEAST(user_id, friend_id), GREATEST(user_id, friend_id))
DO UPDATE SET status = 'ACCEPTED', action_by = $4, updated_at = now()
`

type UpsertFriendshipAcceptedParams struct {
	ID       uuid.UUID   `json:"id"`
	UserID   uuid.UUID   `json:"user_id"`
	FriendID uuid.UUID   `json:"friend_id"`
	ActionBy pgtype.UUID `json:"action_by"`
}

func (q *Queries) UpsertFriendshipAccepted(ctx context.Context, arg UpsertFriendshipAcceptedParams) error {
	_, err := q.db.Exec(ctx, upsertFriendshipAccepted,
		arg.ID,
		arg.UserID,
		arg.FriendID,
		arg.ActionBy,
	)
	return err
}

const upsertFriendshipAcceptedNoAction = `-- name: UpsertFriendshipAcceptedNoAction :exec
INSERT INTO friendships (id, user_id, friend_id, status, action_by) VALUES ($1, $2, $3, 'ACCEPTED', $4)
ON CONFLICT (LEAST(user_id, friend_id), GREATEST(user_id, friend_id))
DO UPDATE SET status = 'ACCEPTED', updated_at = now()
`

type UpsertFriendshipAcceptedNoActionParams struct {
	ID       uuid.UUID   `json:"id"`
	UserID   uuid.UUID   `json:"user_id"`
	FriendID uuid.UUID   `json:"friend_id"`
	ActionBy pgtype.UUID `json:"action_by"`
}

func (q *Queries) UpsertFriendshipAcceptedNoAction(ctx context.Context, arg UpsertFriendshipAcceptedNoActionParams) error {
	_, err := q.db.Exec(ctx, upsertFriendshipAcceptedNoAction,
		arg.ID,
		arg.UserID,
		arg.FriendID,
		arg.ActionBy,
	)
	return err
}
