// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptGroupInviteMember = `-- name: AcceptGroupInviteMember :exec
INSERT INTO group_members (group_id, user_id, role) VALUES ($1, $2, 'MEMBER')
`

type AcceptGroupInviteMemberParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) AcceptGroupInviteMember(ctx context.Context, arg AcceptGroupInviteMemberParams) error {
	_, err := q.db.Exec(ctx, acceptGroupInviteMember, arg.GroupID, arg.UserID)
	return err
}

const addGroupMember = `-- name: AddGroupMember :exec
INSERT INTO group_members (group_id, user_id, role) VALUES ($1, $2, $3) ON CONFLICT DO NOTHING
`

type AddGroupMemberParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
	Role    string    `json:"role"`
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error {
	_, err := q.db.Exec(ctx, addGroupMember, arg.GroupID, arg.UserID, arg.Role)
	return err
}

const archiveGroup = `-- name: ArchiveGroup :exec
UPDATE groups SET archived_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) ArchiveGroup(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, archiveGroup, id)
	return err
}

const checkAlreadyMember = `-- name: CheckAlreadyMember :one
SELECT EXISTS(SELECT 1 FROM group_members WHERE group_id = $1 AND user_id = $2) AS already_member
`

type CheckAlreadyMemberParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) CheckAlreadyMember(ctx context.Context, arg CheckAlreadyMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkAlreadyMember, arg.GroupID, arg.UserID)
	var already_member bool
	err := row.Scan(&already_member)
	return already_member, err
}

const checkFriendship = `-- name: CheckFriendship :one
SELECT EXISTS(
    SELECT 1 FROM friendships
    WHERE LEAST(user_id, friend_id) = LEAST($1::uuid, $2::uuid)
      AND GREATEST(user_id, friend_id) = GREATEST($1::uuid, $2::uuid)
      AND status = 'ACCEPTED'
) AS is_friend
`

type CheckFriendshipParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 pgtype.UUID `json:"column_2"`
}

func (q *Queries) CheckFriendship(ctx context.Context, arg CheckFriendshipParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkFriendship, arg.Column1, arg.Column2)
	var is_friend bool
	err := row.Scan(&is_friend)
	return is_friend, err
}

const createGroup = `-- name: CreateGroup :exec
INSERT INTO groups (id, name, description, avatar_url, currency, created_by, information)
VALUES ($1, $2, $3, NULLIF($4, ''), $5, $6, $7)
`

type CreateGroupParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Column4     interface{} `json:"column_4"`
	Currency    string      `json:"currency"`
	CreatedBy   uuid.UUID   `json:"created_by"`
	Information pgtype.Text `json:"information"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) error {
	_, err := q.db.Exec(ctx, createGroup,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Column4,
		arg.Currency,
		arg.CreatedBy,
		arg.Information,
	)
	return err
}

const createGroupInvite = `-- name: CreateGroupInvite :exec
INSERT INTO group_invites (id, group_id, email, token_hash, invited_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (group_id, lower(email)) WHERE status = 'PENDING'
DO UPDATE SET token_hash = $4, invited_by = $5, created_at = now(), expires_at = now() + interval '7 days'
`

type CreateGroupInviteParams struct {
	ID        uuid.UUID `json:"id"`
	GroupID   uuid.UUID `json:"group_id"`
	Email     string    `json:"email"`
	TokenHash string    `json:"token_hash"`
	InvitedBy uuid.UUID `json:"invited_by"`
}

func (q *Queries) CreateGroupInvite(ctx context.Context, arg CreateGroupInviteParams) error {
	_, err := q.db.Exec(ctx, createGroupInvite,
		arg.ID,
		arg.GroupID,
		arg.Email,
		arg.TokenHash,
		arg.InvitedBy,
	)
	return err
}

const createGroupMember = `-- name: CreateGroupMember :exec
INSERT INTO group_members (group_id, user_id, role) VALUES ($1, $2, $3)
`

type CreateGroupMemberParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
	Role    string    `json:"role"`
}

func (q *Queries) CreateGroupMember(ctx context.Context, arg CreateGroupMemberParams) error {
	_, err := q.db.Exec(ctx, createGroupMember, arg.GroupID, arg.UserID, arg.Role)
	return err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroup, id)
	return err
}

const deleteGroupExpenseAttachments = `-- name: DeleteGroupExpenseAttachments :exec
DELETE FROM expense_attachments WHERE expense_id IN (SELECT id FROM expenses WHERE group_id = $1)
`

func (q *Queries) DeleteGroupExpenseAttachments(ctx context.Context, groupID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroupExpenseAttachments, groupID)
	return err
}

const deleteGroupExpenseSplits = `-- name: DeleteGroupExpenseSplits :exec
DELETE FROM expense_splits WHERE expense_id IN (SELECT id FROM expenses WHERE group_id = $1)
`

func (q *Queries) DeleteGroupExpenseSplits(ctx context.Context, groupID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroupExpenseSplits, groupID)
	return err
}

const deleteGroupExpenses = `-- name: DeleteGroupExpenses :exec
DELETE FROM expenses WHERE group_id = $1
`

func (q *Queries) DeleteGroupExpenses(ctx context.Context, groupID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroupExpenses, groupID)
	return err
}

const deleteGroupRecurring = `-- name: DeleteGroupRecurring :exec
DELETE FROM recurring_expenses WHERE group_id = $1
`

func (q *Queries) DeleteGroupRecurring(ctx context.Context, groupID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroupRecurring, groupID)
	return err
}

const deleteGroupSettlements = `-- name: DeleteGroupSettlements :exec
DELETE FROM settlements WHERE group_id = $1
`

func (q *Queries) DeleteGroupSettlements(ctx context.Context, groupID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroupSettlements, groupID)
	return err
}

const ensureFriendship = `-- name: EnsureFriendship :exec
INSERT INTO friendships (id, user_id, friend_id, status, action_by)
VALUES ($1, LEAST($2::uuid, $3::uuid), GREATEST($2::uuid, $3::uuid), 'ACCEPTED', $3)
ON CONFLICT (LEAST(user_id, friend_id), GREATEST(user_id, friend_id))
DO UPDATE SET status = 'ACCEPTED', action_by = $3, updated_at = now()
`

type EnsureFriendshipParams struct {
	ID       uuid.UUID   `json:"id"`
	Column2  pgtype.UUID `json:"column_2"`
	ActionBy pgtype.UUID `json:"action_by"`
}

func (q *Queries) EnsureFriendship(ctx context.Context, arg EnsureFriendshipParams) error {
	_, err := q.db.Exec(ctx, ensureFriendship, arg.ID, arg.Column2, arg.ActionBy)
	return err
}

const getGroup = `-- name: GetGroup :one
SELECT
    g.name,
    g.description,
    coalesce(g.avatar_url, '') AS avatar_url,
    g.currency,
    coalesce(g.group_type, 'OTHER') AS group_type,
    coalesce(g.simplify_debts, true) AS simplify_debts,
    g.created_by,
    g.created_at,
    g.updated_at,
    g.archived_at,
    g.information
FROM groups g
WHERE g.id = $1
`

type GetGroupRow struct {
	Name          string             `json:"name"`
	Description   string             `json:"description"`
	AvatarUrl     string             `json:"avatar_url"`
	Currency      string             `json:"currency"`
	GroupType     string             `json:"group_type"`
	SimplifyDebts bool               `json:"simplify_debts"`
	CreatedBy     uuid.UUID          `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt    pgtype.Timestamptz `json:"archived_at"`
	Information   pgtype.Text        `json:"information"`
}

func (q *Queries) GetGroup(ctx context.Context, id uuid.UUID) (GetGroupRow, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i GetGroupRow
	err := row.Scan(
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.Currency,
		&i.GroupType,
		&i.SimplifyDebts,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.Information,
	)
	return i, err
}

const getInviteByHash = `-- name: GetInviteByHash :one
SELECT id, group_id, email, invited_by, status FROM group_invites WHERE token_hash = $1
`

type GetInviteByHashRow struct {
	ID        uuid.UUID `json:"id"`
	GroupID   uuid.UUID `json:"group_id"`
	Email     string    `json:"email"`
	InvitedBy uuid.UUID `json:"invited_by"`
	Status    string    `json:"status"`
}

func (q *Queries) GetInviteByHash(ctx context.Context, tokenHash string) (GetInviteByHashRow, error) {
	row := q.db.QueryRow(ctx, getInviteByHash, tokenHash)
	var i GetInviteByHashRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Email,
		&i.InvitedBy,
		&i.Status,
	)
	return i, err
}

const getInviteToken = `-- name: GetInviteToken :one
SELECT invite_token FROM groups WHERE id = $1
`

func (q *Queries) GetInviteToken(ctx context.Context, id uuid.UUID) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getInviteToken, id)
	var invite_token pgtype.Text
	err := row.Scan(&invite_token)
	return invite_token, err
}

const getMemberRole = `-- name: GetMemberRole :one
SELECT role FROM group_members WHERE group_id = $1 AND user_id = $2
`

type GetMemberRoleParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getMemberRole, arg.GroupID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getUserEmail = `-- name: GetUserEmail :one
SELECT lower(email) FROM users WHERE id = $1
`

func (q *Queries) GetUserEmail(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserEmail, id)
	var lower string
	err := row.Scan(&lower)
	return lower, err
}

const insertActivityEvent = `-- name: InsertActivityEvent :exec
INSERT INTO activity_events (group_id, actor_id, type, entity_type, entity_id, payload)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertActivityEventParams struct {
	GroupID    uuid.UUID `json:"group_id"`
	ActorID    uuid.UUID `json:"actor_id"`
	Type       string    `json:"type"`
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
	Payload    []byte    `json:"payload"`
}

func (q *Queries) InsertActivityEvent(ctx context.Context, arg InsertActivityEventParams) error {
	_, err := q.db.Exec(ctx, insertActivityEvent,
		arg.GroupID,
		arg.ActorID,
		arg.Type,
		arg.EntityType,
		arg.EntityID,
		arg.Payload,
	)
	return err
}

const isMember = `-- name: IsMember :one

SELECT role FROM group_members WHERE group_id = $1 AND user_id = $2
`

type IsMemberParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

// Groups domain queries for sqlc with pgx/v5.
// These replace manual Pool.Query/Exec calls in internal/groups/handlers.go
// Handler usage: Handler{Pool *pgxpool.Pool, Queries *db.Queries} where Queries wraps the pool.
// Checks membership and returns role if present. Used ~30+ times across handlers.
func (q *Queries) IsMember(ctx context.Context, arg IsMemberParams) (string, error) {
	row := q.db.QueryRow(ctx, isMember, arg.GroupID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const leaveGroup = `-- name: LeaveGroup :exec
DELETE FROM group_members WHERE group_id = $1 AND user_id = $2
`

type LeaveGroupParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) LeaveGroup(ctx context.Context, arg LeaveGroupParams) error {
	_, err := q.db.Exec(ctx, leaveGroup, arg.GroupID, arg.UserID)
	return err
}

const listGroupInvites = `-- name: ListGroupInvites :many
SELECT id, email, status, invited_by, created_at, expires_at
FROM group_invites
WHERE group_id = $1 AND status = 'PENDING'
ORDER BY created_at DESC
`

type ListGroupInvitesRow struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	Status    string             `json:"status"`
	InvitedBy uuid.UUID          `json:"invited_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) ListGroupInvites(ctx context.Context, groupID uuid.UUID) ([]ListGroupInvitesRow, error) {
	rows, err := q.db.Query(ctx, listGroupInvites, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupInvitesRow
	for rows.Next() {
		var i ListGroupInvitesRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Status,
			&i.InvitedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT
    u.id,
    u.name,
    coalesce(u.avatar_url, '') AS avatar_url,
    gm.role,
    gm.joined_at
FROM group_members gm
JOIN users u ON u.id = gm.user_id
WHERE gm.group_id = $1
ORDER BY gm.joined_at
`

type ListGroupMembersRow struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	AvatarUrl string             `json:"avatar_url"`
	Role      string             `json:"role"`
	JoinedAt  pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) ListGroupMembers(ctx context.Context, groupID uuid.UUID) ([]ListGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupMembersRow
	for rows.Next() {
		var i ListGroupMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AvatarUrl,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT
    g.id,
    g.name,
    g.description,
    coalesce(g.avatar_url, '') AS avatar_url,
    g.currency,
    coalesce(g.group_type, 'OTHER') AS group_type,
    coalesce(g.simplify_debts, true) AS simplify_debts,
    g.created_by,
    g.created_at,
    g.updated_at,
    g.archived_at,
    g.information
FROM groups g
JOIN group_members gm ON gm.group_id = g.id
WHERE gm.user_id = $1
  AND g.archived_at IS NULL
  AND g.group_type <> 'DIRECT'
ORDER BY g.updated_at DESC
`

type ListGroupsRow struct {
	ID            uuid.UUID          `json:"id"`
	Name          string             `json:"name"`
	Description   string             `json:"description"`
	AvatarUrl     string             `json:"avatar_url"`
	Currency      string             `json:"currency"`
	GroupType     string             `json:"group_type"`
	SimplifyDebts bool               `json:"simplify_debts"`
	CreatedBy     uuid.UUID          `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt    pgtype.Timestamptz `json:"archived_at"`
	Information   pgtype.Text        `json:"information"`
}

func (q *Queries) ListGroups(ctx context.Context, userID uuid.UUID) ([]ListGroupsRow, error) {
	rows, err := q.db.Query(ctx, listGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupsRow
	for rows.Next() {
		var i ListGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.AvatarUrl,
			&i.Currency,
			&i.GroupType,
			&i.SimplifyDebts,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.Information,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsFiltered = `-- name: ListGroupsFiltered :many
SELECT
    g.id,
    g.name,
    g.description,
    coalesce(g.avatar_url, '') AS avatar_url,
    g.currency,
    coalesce(g.group_type, 'OTHER') AS group_type,
    coalesce(g.simplify_debts, true) AS simplify_debts,
    g.created_by,
    g.created_at,
    g.updated_at,
    g.archived_at,
    g.information
FROM groups g
JOIN group_members gm ON gm.group_id = g.id
WHERE gm.user_id = $1
  AND g.archived_at IS NULL
  AND g.group_type <> 'DIRECT'
  AND g.name ILIKE '%' || $2 || '%'
ORDER BY g.updated_at DESC
`

type ListGroupsFilteredParams struct {
	UserID  uuid.UUID   `json:"user_id"`
	Column2 pgtype.Text `json:"column_2"`
}

type ListGroupsFilteredRow struct {
	ID            uuid.UUID          `json:"id"`
	Name          string             `json:"name"`
	Description   string             `json:"description"`
	AvatarUrl     string             `json:"avatar_url"`
	Currency      string             `json:"currency"`
	GroupType     string             `json:"group_type"`
	SimplifyDebts bool               `json:"simplify_debts"`
	CreatedBy     uuid.UUID          `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt    pgtype.Timestamptz `json:"archived_at"`
	Information   pgtype.Text        `json:"information"`
}

func (q *Queries) ListGroupsFiltered(ctx context.Context, arg ListGroupsFilteredParams) ([]ListGroupsFilteredRow, error) {
	rows, err := q.db.Query(ctx, listGroupsFiltered, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupsFilteredRow
	for rows.Next() {
		var i ListGroupsFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.AvatarUrl,
			&i.Currency,
			&i.GroupType,
			&i.SimplifyDebts,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.Information,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyInvites = `-- name: ListMyInvites :many
SELECT gi.id, gi.group_id, g.name AS group_name, gi.email, gi.created_at
FROM group_invites gi
JOIN groups g ON g.id = gi.group_id
WHERE lower(gi.email) = lower($1) AND gi.status = 'PENDING' AND gi.expires_at > now()
`

type ListMyInvitesRow struct {
	ID        uuid.UUID          `json:"id"`
	GroupID   uuid.UUID          `json:"group_id"`
	GroupName string             `json:"group_name"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListMyInvites(ctx context.Context, lower string) ([]ListMyInvitesRow, error) {
	rows, err := q.db.Query(ctx, listMyInvites, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyInvitesRow
	for rows.Next() {
		var i ListMyInvitesRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.GroupName,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInviteAccepted = `-- name: MarkInviteAccepted :exec
UPDATE group_invites SET status = 'ACCEPTED' WHERE id = $1 AND status = 'PENDING'
`

func (q *Queries) MarkInviteAccepted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markInviteAccepted, id)
	return err
}

const removeGroupMember = `-- name: RemoveGroupMember :exec
DELETE FROM group_members WHERE group_id = $1 AND user_id = $2
`

type RemoveGroupMemberParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error {
	_, err := q.db.Exec(ctx, removeGroupMember, arg.GroupID, arg.UserID)
	return err
}

const setInviteToken = `-- name: SetInviteToken :exec
UPDATE groups SET invite_token = $2 WHERE id = $1
`

type SetInviteTokenParams struct {
	ID          uuid.UUID   `json:"id"`
	InviteToken pgtype.Text `json:"invite_token"`
}

func (q *Queries) SetInviteToken(ctx context.Context, arg SetInviteTokenParams) error {
	_, err := q.db.Exec(ctx, setInviteToken, arg.ID, arg.InviteToken)
	return err
}

const updateGroupAvatar = `-- name: UpdateGroupAvatar :exec
UPDATE groups SET avatar_url = $2, updated_at = now() WHERE id = $1
`

type UpdateGroupAvatarParams struct {
	ID        uuid.UUID   `json:"id"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) UpdateGroupAvatar(ctx context.Context, arg UpdateGroupAvatarParams) error {
	_, err := q.db.Exec(ctx, updateGroupAvatar, arg.ID, arg.AvatarUrl)
	return err
}

const updateGroupCurrency = `-- name: UpdateGroupCurrency :exec
UPDATE groups SET currency = $2, updated_at = now() WHERE id = $1
`

type UpdateGroupCurrencyParams struct {
	ID       uuid.UUID `json:"id"`
	Currency string    `json:"currency"`
}

func (q *Queries) UpdateGroupCurrency(ctx context.Context, arg UpdateGroupCurrencyParams) error {
	_, err := q.db.Exec(ctx, updateGroupCurrency, arg.ID, arg.Currency)
	return err
}

const updateGroupDescription = `-- name: UpdateGroupDescription :exec
UPDATE groups SET description = $2, updated_at = now() WHERE id = $1
`

type UpdateGroupDescriptionParams struct {
	ID          uuid.UUID `json:"id"`
	Description string    `json:"description"`
}

func (q *Queries) UpdateGroupDescription(ctx context.Context, arg UpdateGroupDescriptionParams) error {
	_, err := q.db.Exec(ctx, updateGroupDescription, arg.ID, arg.Description)
	return err
}

const updateGroupInformation = `-- name: UpdateGroupInformation :exec
UPDATE groups SET information = $2, updated_at = now() WHERE id = $1
`

type UpdateGroupInformationParams struct {
	ID          uuid.UUID   `json:"id"`
	Information pgtype.Text `json:"information"`
}

func (q *Queries) UpdateGroupInformation(ctx context.Context, arg UpdateGroupInformationParams) error {
	_, err := q.db.Exec(ctx, updateGroupInformation, arg.ID, arg.Information)
	return err
}

const updateGroupName = `-- name: UpdateGroupName :exec
UPDATE groups SET name = $2, updated_at = now() WHERE id = $1
`

type UpdateGroupNameParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateGroupName(ctx context.Context, arg UpdateGroupNameParams) error {
	_, err := q.db.Exec(ctx, updateGroupName, arg.ID, arg.Name)
	return err
}

const updateGroupSimplifyDebts = `-- name: UpdateGroupSimplifyDebts :exec
UPDATE groups SET simplify_debts = $2, updated_at = now() WHERE id = $1
`

type UpdateGroupSimplifyDebtsParams struct {
	ID            uuid.UUID `json:"id"`
	SimplifyDebts bool      `json:"simplify_debts"`
}

func (q *Queries) UpdateGroupSimplifyDebts(ctx context.Context, arg UpdateGroupSimplifyDebtsParams) error {
	_, err := q.db.Exec(ctx, updateGroupSimplifyDebts, arg.ID, arg.SimplifyDebts)
	return err
}

const updateGroupType = `-- name: UpdateGroupType :exec
UPDATE groups SET group_type = $2, updated_at = now() WHERE id = $1
`

type UpdateGroupTypeParams struct {
	ID        uuid.UUID `json:"id"`
	GroupType string    `json:"group_type"`
}

func (q *Queries) UpdateGroupType(ctx context.Context, arg UpdateGroupTypeParams) error {
	_, err := q.db.Exec(ctx, updateGroupType, arg.ID, arg.GroupType)
	return err
}

const updateMemberRole = `-- name: UpdateMemberRole :exec
UPDATE group_members SET role = $3 WHERE group_id = $1 AND user_id = $2
`

type UpdateMemberRoleParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
	Role    string    `json:"role"`
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateMemberRole, arg.GroupID, arg.UserID, arg.Role)
	return err
}
