// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityEvent struct {
	ID         uuid.UUID          `json:"id"`
	GroupID    uuid.UUID          `json:"group_id"`
	ActorID    uuid.UUID          `json:"actor_id"`
	Type       string             `json:"type"`
	EntityType string             `json:"entity_type"`
	EntityID   uuid.UUID          `json:"entity_id"`
	Payload    []byte             `json:"payload"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Category struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Icon      string             `json:"icon"`
	Color     string             `json:"color"`
	IsSystem  bool               `json:"is_system"`
	OwnerID   uuid.UUID          `json:"owner_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Grouping  pgtype.Text        `json:"grouping"`
}

type EmailVerificationToken struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	VerifiedAt pgtype.Timestamptz `json:"verified_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Expense struct {
	ID               uuid.UUID          `json:"id"`
	GroupID          uuid.UUID          `json:"group_id"`
	Description      string             `json:"description"`
	Amount           int64              `json:"amount"`
	Currency         string             `json:"currency"`
	SplitMode        string             `json:"split_mode"`
	PaidBy           uuid.UUID          `json:"paid_by"`
	CategoryID       uuid.UUID          `json:"category_id"`
	Notes            string             `json:"notes"`
	ExpenseDate      pgtype.Date        `json:"expense_date"`
	CreatedBy        uuid.UUID          `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	ExchangeRate     pgtype.Numeric     `json:"exchange_rate"`
	BaseCurrency     pgtype.Text        `json:"base_currency"`
	BaseAmount       pgtype.Int8        `json:"base_amount"`
	OriginalAmount   pgtype.Int8        `json:"original_amount"`
	OriginalCurrency pgtype.Text        `json:"original_currency"`
	ConversionRate   pgtype.Numeric     `json:"conversion_rate"`
}

type ExpenseAttachment struct {
	ID        uuid.UUID          `json:"id"`
	ExpenseID uuid.UUID          `json:"expense_id"`
	UserID    uuid.UUID          `json:"user_id"`
	FileUrl   string             `json:"file_url"`
	FileName  string             `json:"file_name"`
	MimeType  string             `json:"mime_type"`
	SizeBytes int32              `json:"size_bytes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ExpenseComment struct {
	ID        uuid.UUID          `json:"id"`
	ExpenseID uuid.UUID          `json:"expense_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type ExpenseSplit struct {
	ID         uuid.UUID          `json:"id"`
	ExpenseID  uuid.UUID          `json:"expense_id"`
	UserID     uuid.UUID          `json:"user_id"`
	Amount     int64              `json:"amount"`
	Percentage pgtype.Numeric     `json:"percentage"`
	Shares     pgtype.Int4        `json:"shares"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type FriendInvite struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	TokenHash string             `json:"token_hash"`
	InvitedBy uuid.UUID          `json:"invited_by"`
	Status    string             `json:"status"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Friendship struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	FriendID  uuid.UUID          `json:"friend_id"`
	Status    string             `json:"status"`
	ActionBy  pgtype.UUID        `json:"action_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Group struct {
	ID            uuid.UUID          `json:"id"`
	Name          string             `json:"name"`
	Description   string             `json:"description"`
	AvatarUrl     pgtype.Text        `json:"avatar_url"`
	Currency      string             `json:"currency"`
	CreatedBy     uuid.UUID          `json:"created_by"`
	ArchivedAt    pgtype.Timestamptz `json:"archived_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	SimplifyDebts bool               `json:"simplify_debts"`
	GroupType     string             `json:"group_type"`
	InviteToken   pgtype.Text        `json:"invite_token"`
	DirectKey     pgtype.Text        `json:"direct_key"`
	Information   pgtype.Text        `json:"information"`
}

type GroupInvite struct {
	ID        uuid.UUID          `json:"id"`
	GroupID   uuid.UUID          `json:"group_id"`
	Email     string             `json:"email"`
	TokenHash string             `json:"token_hash"`
	InvitedBy uuid.UUID          `json:"invited_by"`
	Status    string             `json:"status"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type GroupMember struct {
	GroupID  uuid.UUID          `json:"group_id"`
	UserID   uuid.UUID          `json:"user_id"`
	Role     string             `json:"role"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type Notification struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Type      string             `json:"type"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	Data      []byte             `json:"data"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type NotificationPreference struct {
	UserID               uuid.UUID          `json:"user_id"`
	EmailEnabled         bool               `json:"email_enabled"`
	PushEnabled          bool               `json:"push_enabled"`
	FriendRequestEnabled bool               `json:"friend_request_enabled"`
	ExpenseEnabled       bool               `json:"expense_enabled"`
	SettlementEnabled    bool               `json:"settlement_enabled"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type OauthIdentity struct {
	Provider  string             `json:"provider"`
	Subject   string             `json:"subject"`
	UserID    uuid.UUID          `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PasswordResetToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PersonalBudget struct {
	UserID    uuid.UUID          `json:"user_id"`
	Month     pgtype.Date        `json:"month"`
	Amount    int64              `json:"amount"`
	Currency  string             `json:"currency"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type PersonalExpense struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Description  string             `json:"description"`
	Amount       int64              `json:"amount"`
	Currency     string             `json:"currency"`
	CategoryID   uuid.UUID          `json:"category_id"`
	Notes        string             `json:"notes"`
	ExpenseDate  pgtype.Date        `json:"expense_date"`
	BaseCurrency pgtype.Text        `json:"base_currency"`
	ExchangeRate pgtype.Numeric     `json:"exchange_rate"`
	BaseAmount   pgtype.Int8        `json:"base_amount"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type RecurringExpense struct {
	ID          uuid.UUID          `json:"id"`
	GroupID     uuid.UUID          `json:"group_id"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	Description string             `json:"description"`
	Amount      int64              `json:"amount"`
	Currency    string             `json:"currency"`
	CategoryID  uuid.UUID          `json:"category_id"`
	SplitMode   string             `json:"split_mode"`
	Splits      []byte             `json:"splits"`
	PaidBy      uuid.UUID          `json:"paid_by"`
	Frequency   string             `json:"frequency"`
	NextRunAt   pgtype.Timestamptz `json:"next_run_at"`
	LastRunAt   pgtype.Timestamptz `json:"last_run_at"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	UserAgent        pgtype.Text        `json:"user_agent"`
	Ip               pgtype.Text        `json:"ip"`
	RotatedFrom      pgtype.UUID        `json:"rotated_from"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt       pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Settlement struct {
	ID        uuid.UUID          `json:"id"`
	GroupID   uuid.UUID          `json:"group_id"`
	FromUser  uuid.UUID          `json:"from_user"`
	ToUser    uuid.UUID          `json:"to_user"`
	Amount    int64              `json:"amount"`
	Currency  string             `json:"currency"`
	Note      string             `json:"note"`
	SettledAt pgtype.Timestamptz `json:"settled_at"`
	CreatedBy uuid.UUID          `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	Email           string             `json:"email"`
	PasswordHash    pgtype.Text        `json:"password_hash"`
	AvatarUrl       pgtype.Text        `json:"avatar_url"`
	DefaultCurrency string             `json:"default_currency"`
	Timezone        string             `json:"timezone"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	IsAnonymous     bool               `json:"is_anonymous"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	BankQrUrl       pgtype.Text        `json:"bank_qr_url"`
	BankName        pgtype.Text        `json:"bank_name"`
	PaymentHandle   pgtype.Text        `json:"payment_handle"`
}
