// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkNotificationExists = `-- name: CheckNotificationExists :one
SELECT EXISTS (SELECT 1 FROM notifications WHERE id = $1 AND user_id = $2) AS exists
`

type CheckNotificationExistsParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CheckNotificationExists(ctx context.Context, arg CheckNotificationExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkNotificationExists, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getNotificationPreferences = `-- name: GetNotificationPreferences :one

SELECT email_enabled, push_enabled, friend_request_enabled, expense_enabled, settlement_enabled
FROM notification_preferences
WHERE user_id = $1
`

type GetNotificationPreferencesRow struct {
	EmailEnabled         bool `json:"email_enabled"`
	PushEnabled          bool `json:"push_enabled"`
	FriendRequestEnabled bool `json:"friend_request_enabled"`
	ExpenseEnabled       bool `json:"expense_enabled"`
	SettlementEnabled    bool `json:"settlement_enabled"`
}

// Notifications domain queries for sqlc with pgx/v5.
// These replace manual Pool.Query/Exec calls in internal/notifications/handlers.go
// Handler usage: Handler{Pool *pgxpool.Pool, Queries *db.Queries} where Queries wraps the pool.
func (q *Queries) GetNotificationPreferences(ctx context.Context, userID uuid.UUID) (GetNotificationPreferencesRow, error) {
	row := q.db.QueryRow(ctx, getNotificationPreferences, userID)
	var i GetNotificationPreferencesRow
	err := row.Scan(
		&i.EmailEnabled,
		&i.PushEnabled,
		&i.FriendRequestEnabled,
		&i.ExpenseEnabled,
		&i.SettlementEnabled,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT n.id, n.type, n.title, n.body, n.data, n.read_at, n.created_at
FROM notifications n
WHERE n.user_id = $1
ORDER BY n.created_at DESC, n.id DESC
LIMIT $2
`

type ListNotificationsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

type ListNotificationsRow struct {
	ID        uuid.UUID          `json:"id"`
	Type      string             `json:"type"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	Data      []byte             `json:"data"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationsRow
	for rows.Next() {
		var i ListNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Data,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsWithCursor = `-- name: ListNotificationsWithCursor :many
SELECT n.id, n.type, n.title, n.body, n.data, n.read_at, n.created_at
FROM notifications n
WHERE n.user_id = $1
  AND (n.created_at, n.id) < (SELECT cursor.created_at, cursor.id FROM notifications cursor WHERE cursor.id = $2)
ORDER BY n.created_at DESC, n.id DESC
LIMIT $3
`

type ListNotificationsWithCursorParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
	Limit  int32     `json:"limit"`
}

type ListNotificationsWithCursorRow struct {
	ID        uuid.UUID          `json:"id"`
	Type      string             `json:"type"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	Data      []byte             `json:"data"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListNotificationsWithCursor(ctx context.Context, arg ListNotificationsWithCursorParams) ([]ListNotificationsWithCursorRow, error) {
	rows, err := q.db.Query(ctx, listNotificationsWithCursor, arg.UserID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationsWithCursorRow
	for rows.Next() {
		var i ListNotificationsWithCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Data,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET read_at = now() WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :execrows
UPDATE notifications SET read_at = now() WHERE id = $1 AND user_id = $2 AND read_at IS NULL
`

type MarkNotificationReadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertNotificationPreferences = `-- name: UpsertNotificationPreferences :exec
INSERT INTO notification_preferences (user_id, email_enabled, push_enabled, friend_request_enabled, expense_enabled, settlement_enabled)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id) DO UPDATE SET
    email_enabled = EXCLUDED.email_enabled,
    push_enabled = EXCLUDED.push_enabled,
    friend_request_enabled = EXCLUDED.friend_request_enabled,
    expense_enabled = EXCLUDED.expense_enabled,
    settlement_enabled = EXCLUDED.settlement_enabled
`

type UpsertNotificationPreferencesParams struct {
	UserID               uuid.UUID `json:"user_id"`
	EmailEnabled         bool      `json:"email_enabled"`
	PushEnabled          bool      `json:"push_enabled"`
	FriendRequestEnabled bool      `json:"friend_request_enabled"`
	ExpenseEnabled       bool      `json:"expense_enabled"`
	SettlementEnabled    bool      `json:"settlement_enabled"`
}

func (q *Queries) UpsertNotificationPreferences(ctx context.Context, arg UpsertNotificationPreferencesParams) error {
	_, err := q.db.Exec(ctx, upsertNotificationPreferences,
		arg.UserID,
		arg.EmailEnabled,
		arg.PushEnabled,
		arg.FriendRequestEnabled,
		arg.ExpenseEnabled,
		arg.SettlementEnabled,
	)
	return err
}
