// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: personal.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkPersonalExpenseExists = `-- name: CheckPersonalExpenseExists :one
SELECT EXISTS(SELECT 1 FROM personal_expenses WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL) AS exists
`

type CheckPersonalExpenseExistsParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CheckPersonalExpenseExists(ctx context.Context, arg CheckPersonalExpenseExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkPersonalExpenseExists, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createPersonalExpense = `-- name: CreatePersonalExpense :exec
INSERT INTO personal_expenses (id, user_id, description, amount, currency, category_id, notes, expense_date, base_currency, exchange_rate, base_amount)
VALUES ($1, $2, $3, $4, $5, NULLIF($6::uuid, '00000000-0000-0000-0000-000000000000'::uuid), $7, $8, $9, $10, $11)
`

type CreatePersonalExpenseParams struct {
	ID           uuid.UUID      `json:"id"`
	UserID       uuid.UUID      `json:"user_id"`
	Description  string         `json:"description"`
	Amount       int64          `json:"amount"`
	Currency     string         `json:"currency"`
	Column6      pgtype.UUID    `json:"column_6"`
	Notes        string         `json:"notes"`
	ExpenseDate  pgtype.Date    `json:"expense_date"`
	BaseCurrency pgtype.Text    `json:"base_currency"`
	ExchangeRate pgtype.Numeric `json:"exchange_rate"`
	BaseAmount   pgtype.Int8    `json:"base_amount"`
}

func (q *Queries) CreatePersonalExpense(ctx context.Context, arg CreatePersonalExpenseParams) error {
	_, err := q.db.Exec(ctx, createPersonalExpense,
		arg.ID,
		arg.UserID,
		arg.Description,
		arg.Amount,
		arg.Currency,
		arg.Column6,
		arg.Notes,
		arg.ExpenseDate,
		arg.BaseCurrency,
		arg.ExchangeRate,
		arg.BaseAmount,
	)
	return err
}

const getPersonalBudget = `-- name: GetPersonalBudget :one

SELECT amount, currency FROM personal_budgets WHERE user_id = $1 AND month = $2
`

type GetPersonalBudgetParams struct {
	UserID uuid.UUID   `json:"user_id"`
	Month  pgtype.Date `json:"month"`
}

type GetPersonalBudgetRow struct {
	Amount   int64  `json:"amount"`
	Currency string `json:"currency"`
}

// Personal domain queries for sqlc with pgx/v5.
// These replace manual Pool.Query/Exec calls in internal/personal/handlers.go
// Handler usage: Handler{Pool *pgxpool.Pool, Queries *db.Queries} where Queries wraps the pool.
// Transaction usage: qtx := h.Queries.WithTx(tx)
func (q *Queries) GetPersonalBudget(ctx context.Context, arg GetPersonalBudgetParams) (GetPersonalBudgetRow, error) {
	row := q.db.QueryRow(ctx, getPersonalBudget, arg.UserID, arg.Month)
	var i GetPersonalBudgetRow
	err := row.Scan(&i.Amount, &i.Currency)
	return i, err
}

const getPersonalExpense = `-- name: GetPersonalExpense :one
SELECT description, amount, currency, category_id, notes, expense_date, created_at, base_currency, exchange_rate, base_amount
FROM personal_expenses
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetPersonalExpenseParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetPersonalExpenseRow struct {
	Description  string             `json:"description"`
	Amount       int64              `json:"amount"`
	Currency     string             `json:"currency"`
	CategoryID   uuid.UUID          `json:"category_id"`
	Notes        string             `json:"notes"`
	ExpenseDate  pgtype.Date        `json:"expense_date"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	BaseCurrency pgtype.Text        `json:"base_currency"`
	ExchangeRate pgtype.Numeric     `json:"exchange_rate"`
	BaseAmount   pgtype.Int8        `json:"base_amount"`
}

func (q *Queries) GetPersonalExpense(ctx context.Context, arg GetPersonalExpenseParams) (GetPersonalExpenseRow, error) {
	row := q.db.QueryRow(ctx, getPersonalExpense, arg.ID, arg.UserID)
	var i GetPersonalExpenseRow
	err := row.Scan(
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.CategoryID,
		&i.Notes,
		&i.ExpenseDate,
		&i.CreatedAt,
		&i.BaseCurrency,
		&i.ExchangeRate,
		&i.BaseAmount,
	)
	return i, err
}

const getPersonalExpenseTotal = `-- name: GetPersonalExpenseTotal :one
SELECT COALESCE(SUM(amount), 0)::bigint AS total FROM personal_expenses WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPersonalExpenseTotal(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getPersonalExpenseTotal, userID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const listPersonalExpenseByCategory = `-- name: ListPersonalExpenseByCategory :many
SELECT COALESCE(c.name, 'Uncategorized') AS category, SUM(pe.amount)::bigint AS total
FROM personal_expenses pe LEFT JOIN categories c ON c.id = pe.category_id
WHERE pe.user_id = $1 AND pe.deleted_at IS NULL
GROUP BY c.name
ORDER BY SUM(pe.amount) DESC
`

type ListPersonalExpenseByCategoryRow struct {
	Category string `json:"category"`
	Total    int64  `json:"total"`
}

func (q *Queries) ListPersonalExpenseByCategory(ctx context.Context, userID uuid.UUID) ([]ListPersonalExpenseByCategoryRow, error) {
	rows, err := q.db.Query(ctx, listPersonalExpenseByCategory, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPersonalExpenseByCategoryRow
	for rows.Next() {
		var i ListPersonalExpenseByCategoryRow
		if err := rows.Scan(&i.Category, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalExpenseByMonth = `-- name: ListPersonalExpenseByMonth :many
SELECT to_char(expense_date, 'YYYY-MM') AS month, SUM(amount)::bigint AS total
FROM personal_expenses
WHERE user_id = $1 AND deleted_at IS NULL AND expense_date >= CURRENT_DATE - INTERVAL '6 months'
GROUP BY month
ORDER BY month
`

type ListPersonalExpenseByMonthRow struct {
	Month string `json:"month"`
	Total int64  `json:"total"`
}

func (q *Queries) ListPersonalExpenseByMonth(ctx context.Context, userID uuid.UUID) ([]ListPersonalExpenseByMonthRow, error) {
	rows, err := q.db.Query(ctx, listPersonalExpenseByMonth, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPersonalExpenseByMonthRow
	for rows.Next() {
		var i ListPersonalExpenseByMonthRow
		if err := rows.Scan(&i.Month, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalExpenses = `-- name: ListPersonalExpenses :many
SELECT id, description, amount, currency, category_id, notes, expense_date, base_currency, exchange_rate, base_amount, created_at
FROM personal_expenses
WHERE user_id = $1
  AND deleted_at IS NULL
  AND ($2::text = '' OR description ILIKE '%' || $2 || '%' OR notes ILIKE '%' || $2 || '%')
ORDER BY expense_date DESC, created_at DESC
LIMIT $3
`

type ListPersonalExpensesParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Column2 string    `json:"column_2"`
	Limit   int32     `json:"limit"`
}

type ListPersonalExpensesRow struct {
	ID           uuid.UUID          `json:"id"`
	Description  string             `json:"description"`
	Amount       int64              `json:"amount"`
	Currency     string             `json:"currency"`
	CategoryID   uuid.UUID          `json:"category_id"`
	Notes        string             `json:"notes"`
	ExpenseDate  pgtype.Date        `json:"expense_date"`
	BaseCurrency pgtype.Text        `json:"base_currency"`
	ExchangeRate pgtype.Numeric     `json:"exchange_rate"`
	BaseAmount   pgtype.Int8        `json:"base_amount"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListPersonalExpenses(ctx context.Context, arg ListPersonalExpensesParams) ([]ListPersonalExpensesRow, error) {
	rows, err := q.db.Query(ctx, listPersonalExpenses, arg.UserID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPersonalExpensesRow
	for rows.Next() {
		var i ListPersonalExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.CategoryID,
			&i.Notes,
			&i.ExpenseDate,
			&i.BaseCurrency,
			&i.ExchangeRate,
			&i.BaseAmount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalExpensesExport = `-- name: ListPersonalExpensesExport :many
SELECT description, amount, currency, expense_date, notes
FROM personal_expenses
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY expense_date DESC
`

type ListPersonalExpensesExportRow struct {
	Description string      `json:"description"`
	Amount      int64       `json:"amount"`
	Currency    string      `json:"currency"`
	ExpenseDate pgtype.Date `json:"expense_date"`
	Notes       string      `json:"notes"`
}

func (q *Queries) ListPersonalExpensesExport(ctx context.Context, userID uuid.UUID) ([]ListPersonalExpensesExportRow, error) {
	rows, err := q.db.Query(ctx, listPersonalExpensesExport, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPersonalExpensesExportRow
	for rows.Next() {
		var i ListPersonalExpensesExportRow
		if err := rows.Scan(
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.ExpenseDate,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePersonalExpense = `-- name: SoftDeletePersonalExpense :exec
UPDATE personal_expenses SET deleted_at = now(), updated_at = now() WHERE id = $1 AND user_id = $2
`

type SoftDeletePersonalExpenseParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) SoftDeletePersonalExpense(ctx context.Context, arg SoftDeletePersonalExpenseParams) error {
	_, err := q.db.Exec(ctx, softDeletePersonalExpense, arg.ID, arg.UserID)
	return err
}

const updatePersonalExpenseAmount = `-- name: UpdatePersonalExpenseAmount :exec
UPDATE personal_expenses SET amount = $1, updated_at = now() WHERE id = $2
`

type UpdatePersonalExpenseAmountParams struct {
	Amount int64     `json:"amount"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdatePersonalExpenseAmount(ctx context.Context, arg UpdatePersonalExpenseAmountParams) error {
	_, err := q.db.Exec(ctx, updatePersonalExpenseAmount, arg.Amount, arg.ID)
	return err
}

const updatePersonalExpenseCategory = `-- name: UpdatePersonalExpenseCategory :exec
UPDATE personal_expenses SET category_id = $1, updated_at = now() WHERE id = $2
`

type UpdatePersonalExpenseCategoryParams struct {
	CategoryID uuid.UUID `json:"category_id"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) UpdatePersonalExpenseCategory(ctx context.Context, arg UpdatePersonalExpenseCategoryParams) error {
	_, err := q.db.Exec(ctx, updatePersonalExpenseCategory, arg.CategoryID, arg.ID)
	return err
}

const updatePersonalExpenseCategoryClear = `-- name: UpdatePersonalExpenseCategoryClear :exec
UPDATE personal_expenses SET category_id = NULL, updated_at = now() WHERE id = $1
`

func (q *Queries) UpdatePersonalExpenseCategoryClear(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updatePersonalExpenseCategoryClear, id)
	return err
}

const updatePersonalExpenseCurrency = `-- name: UpdatePersonalExpenseCurrency :exec
UPDATE personal_expenses SET currency = $1, updated_at = now() WHERE id = $2
`

type UpdatePersonalExpenseCurrencyParams struct {
	Currency string    `json:"currency"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) UpdatePersonalExpenseCurrency(ctx context.Context, arg UpdatePersonalExpenseCurrencyParams) error {
	_, err := q.db.Exec(ctx, updatePersonalExpenseCurrency, arg.Currency, arg.ID)
	return err
}

const updatePersonalExpenseDate = `-- name: UpdatePersonalExpenseDate :exec
UPDATE personal_expenses SET expense_date = $1, updated_at = now() WHERE id = $2
`

type UpdatePersonalExpenseDateParams struct {
	ExpenseDate pgtype.Date `json:"expense_date"`
	ID          uuid.UUID   `json:"id"`
}

func (q *Queries) UpdatePersonalExpenseDate(ctx context.Context, arg UpdatePersonalExpenseDateParams) error {
	_, err := q.db.Exec(ctx, updatePersonalExpenseDate, arg.ExpenseDate, arg.ID)
	return err
}

const updatePersonalExpenseDescription = `-- name: UpdatePersonalExpenseDescription :exec
UPDATE personal_expenses SET description = $1, updated_at = now() WHERE id = $2
`

type UpdatePersonalExpenseDescriptionParams struct {
	Description string    `json:"description"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdatePersonalExpenseDescription(ctx context.Context, arg UpdatePersonalExpenseDescriptionParams) error {
	_, err := q.db.Exec(ctx, updatePersonalExpenseDescription, arg.Description, arg.ID)
	return err
}

const updatePersonalExpenseNotes = `-- name: UpdatePersonalExpenseNotes :exec
UPDATE personal_expenses SET notes = $1, updated_at = now() WHERE id = $2
`

type UpdatePersonalExpenseNotesParams struct {
	Notes string    `json:"notes"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) UpdatePersonalExpenseNotes(ctx context.Context, arg UpdatePersonalExpenseNotesParams) error {
	_, err := q.db.Exec(ctx, updatePersonalExpenseNotes, arg.Notes, arg.ID)
	return err
}

const upsertPersonalBudget = `-- name: UpsertPersonalBudget :exec
INSERT INTO personal_budgets(user_id, month, amount, currency) VALUES($1, $2, $3, $4)
ON CONFLICT(user_id, month) DO UPDATE SET amount = EXCLUDED.amount, currency = EXCLUDED.currency, updated_at = now()
`

type UpsertPersonalBudgetParams struct {
	UserID   uuid.UUID   `json:"user_id"`
	Month    pgtype.Date `json:"month"`
	Amount   int64       `json:"amount"`
	Currency string      `json:"currency"`
}

func (q *Queries) UpsertPersonalBudget(ctx context.Context, arg UpsertPersonalBudgetParams) error {
	_, err := q.db.Exec(ctx, upsertPersonalBudget,
		arg.UserID,
		arg.Month,
		arg.Amount,
		arg.Currency,
	)
	return err
}
