// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptGroupInviteMember(ctx context.Context, arg AcceptGroupInviteMemberParams) error
	AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error
	ArchiveGroup(ctx context.Context, id uuid.UUID) error
	CheckAlreadyMember(ctx context.Context, arg CheckAlreadyMemberParams) (bool, error)
	CheckFriendship(ctx context.Context, arg CheckFriendshipParams) (bool, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) error
	CreateGroupInvite(ctx context.Context, arg CreateGroupInviteParams) error
	CreateGroupMember(ctx context.Context, arg CreateGroupMemberParams) error
	DeleteGroup(ctx context.Context, id uuid.UUID) error
	DeleteGroupExpenseAttachments(ctx context.Context, groupID uuid.UUID) error
	DeleteGroupExpenseSplits(ctx context.Context, groupID uuid.UUID) error
	DeleteGroupExpenses(ctx context.Context, groupID uuid.UUID) error
	DeleteGroupRecurring(ctx context.Context, groupID uuid.UUID) error
	DeleteGroupSettlements(ctx context.Context, groupID uuid.UUID) error
	EnsureFriendship(ctx context.Context, arg EnsureFriendshipParams) error
	GetGroup(ctx context.Context, id uuid.UUID) (GetGroupRow, error)
	GetInviteByHash(ctx context.Context, tokenHash string) (GetInviteByHashRow, error)
	GetInviteToken(ctx context.Context, id uuid.UUID) (pgtype.Text, error)
	GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (string, error)
	GetUserEmail(ctx context.Context, id uuid.UUID) (string, error)
	InsertActivityEvent(ctx context.Context, arg InsertActivityEventParams) error
	// Groups domain queries for sqlc with pgx/v5.
	// These replace manual Pool.Query/Exec calls in internal/groups/handlers.go
	// Handler usage: Handler{Pool *pgxpool.Pool, Queries *db.Queries} where Queries wraps the pool.
	// Checks membership and returns role if present. Used ~30+ times across handlers.
	IsMember(ctx context.Context, arg IsMemberParams) (string, error)
	LeaveGroup(ctx context.Context, arg LeaveGroupParams) error
	ListGroupInvites(ctx context.Context, groupID uuid.UUID) ([]ListGroupInvitesRow, error)
	ListGroupMembers(ctx context.Context, groupID uuid.UUID) ([]ListGroupMembersRow, error)
	ListGroups(ctx context.Context, userID uuid.UUID) ([]ListGroupsRow, error)
	ListGroupsFiltered(ctx context.Context, arg ListGroupsFilteredParams) ([]ListGroupsFilteredRow, error)
	ListMyInvites(ctx context.Context, lower string) ([]ListMyInvitesRow, error)
	MarkInviteAccepted(ctx context.Context, id uuid.UUID) error
	RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error
	SetInviteToken(ctx context.Context, arg SetInviteTokenParams) error
	UpdateGroupAvatar(ctx context.Context, arg UpdateGroupAvatarParams) error
	UpdateGroupCurrency(ctx context.Context, arg UpdateGroupCurrencyParams) error
	UpdateGroupDescription(ctx context.Context, arg UpdateGroupDescriptionParams) error
	UpdateGroupInformation(ctx context.Context, arg UpdateGroupInformationParams) error
	UpdateGroupName(ctx context.Context, arg UpdateGroupNameParams) error
	UpdateGroupSimplifyDebts(ctx context.Context, arg UpdateGroupSimplifyDebtsParams) error
	UpdateGroupType(ctx context.Context, arg UpdateGroupTypeParams) error
	UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error
}

var _ Querier = (*Queries)(nil)
