// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recurring.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkRecurringGroupMember = `-- name: CheckRecurringGroupMember :one
SELECT EXISTS(
    SELECT 1 FROM recurring_expenses re
    JOIN group_members gm ON gm.group_id = re.group_id AND gm.user_id = $2
    WHERE re.id = $1
) AS is_member
`

type CheckRecurringGroupMemberParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CheckRecurringGroupMember(ctx context.Context, arg CheckRecurringGroupMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkRecurringGroupMember, arg.ID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const claimDueRecurring = `-- name: ClaimDueRecurring :one
UPDATE recurring_expenses
SET next_run_at = CASE frequency
                    WHEN 'DAILY' THEN next_run_at + interval '1 day'
                    WHEN 'WEEKLY' THEN next_run_at + interval '7 days'
                    WHEN 'MONTHLY' THEN next_run_at + interval '1 month'
                    ELSE next_run_at + interval '1 year' END,
    last_run_at = next_run_at,
    updated_at = now()
WHERE id = (
    SELECT id FROM recurring_expenses
    WHERE active = true AND next_run_at <= now()
    ORDER BY next_run_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, group_id, description, amount, currency, split_mode, category_id, splits, paid_by, next_run_at
`

type ClaimDueRecurringRow struct {
	ID          uuid.UUID          `json:"id"`
	GroupID     uuid.UUID          `json:"group_id"`
	Description string             `json:"description"`
	Amount      int64              `json:"amount"`
	Currency    string             `json:"currency"`
	SplitMode   string             `json:"split_mode"`
	CategoryID  uuid.UUID          `json:"category_id"`
	Splits      []byte             `json:"splits"`
	PaidBy      uuid.UUID          `json:"paid_by"`
	NextRunAt   pgtype.Timestamptz `json:"next_run_at"`
}

func (q *Queries) ClaimDueRecurring(ctx context.Context) (ClaimDueRecurringRow, error) {
	row := q.db.QueryRow(ctx, claimDueRecurring)
	var i ClaimDueRecurringRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.SplitMode,
		&i.CategoryID,
		&i.Splits,
		&i.PaidBy,
		&i.NextRunAt,
	)
	return i, err
}

const createRecurringActivity = `-- name: CreateRecurringActivity :exec
INSERT INTO activity_events (group_id, actor_id, type, entity_type, entity_id, payload)
VALUES ($1, $2, 'EXPENSE_ADDED', 'expense', $3, json_build_object('description', $4::text, 'recurring', true))
`

type CreateRecurringActivityParams struct {
	GroupID  uuid.UUID `json:"group_id"`
	ActorID  uuid.UUID `json:"actor_id"`
	EntityID uuid.UUID `json:"entity_id"`
	Column4  string    `json:"column_4"`
}

func (q *Queries) CreateRecurringActivity(ctx context.Context, arg CreateRecurringActivityParams) error {
	_, err := q.db.Exec(ctx, createRecurringActivity,
		arg.GroupID,
		arg.ActorID,
		arg.EntityID,
		arg.Column4,
	)
	return err
}

const createRecurringExpense = `-- name: CreateRecurringExpense :exec
INSERT INTO recurring_expenses (id, group_id, created_by, description, amount, currency, category_id, split_mode, splits, paid_by, frequency, next_run_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreateRecurringExpenseParams struct {
	ID          uuid.UUID          `json:"id"`
	GroupID     uuid.UUID          `json:"group_id"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	Description string             `json:"description"`
	Amount      int64              `json:"amount"`
	Currency    string             `json:"currency"`
	CategoryID  uuid.UUID          `json:"category_id"`
	SplitMode   string             `json:"split_mode"`
	Splits      []byte             `json:"splits"`
	PaidBy      uuid.UUID          `json:"paid_by"`
	Frequency   string             `json:"frequency"`
	NextRunAt   pgtype.Timestamptz `json:"next_run_at"`
}

func (q *Queries) CreateRecurringExpense(ctx context.Context, arg CreateRecurringExpenseParams) error {
	_, err := q.db.Exec(ctx, createRecurringExpense,
		arg.ID,
		arg.GroupID,
		arg.CreatedBy,
		arg.Description,
		arg.Amount,
		arg.Currency,
		arg.CategoryID,
		arg.SplitMode,
		arg.Splits,
		arg.PaidBy,
		arg.Frequency,
		arg.NextRunAt,
	)
	return err
}

const createRecurringExpenseInstance = `-- name: CreateRecurringExpenseInstance :exec
INSERT INTO expenses (id, group_id, description, amount, currency, paid_by, split_mode, category_id, expense_date, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9::date, $6)
`

type CreateRecurringExpenseInstanceParams struct {
	ID          uuid.UUID   `json:"id"`
	GroupID     uuid.UUID   `json:"group_id"`
	Description string      `json:"description"`
	Amount      int64       `json:"amount"`
	Currency    string      `json:"currency"`
	PaidBy      uuid.UUID   `json:"paid_by"`
	SplitMode   string      `json:"split_mode"`
	CategoryID  uuid.UUID   `json:"category_id"`
	Column9     pgtype.Date `json:"column_9"`
}

func (q *Queries) CreateRecurringExpenseInstance(ctx context.Context, arg CreateRecurringExpenseInstanceParams) error {
	_, err := q.db.Exec(ctx, createRecurringExpenseInstance,
		arg.ID,
		arg.GroupID,
		arg.Description,
		arg.Amount,
		arg.Currency,
		arg.PaidBy,
		arg.SplitMode,
		arg.CategoryID,
		arg.Column9,
	)
	return err
}

const createRecurringSplit = `-- name: CreateRecurringSplit :exec
INSERT INTO expense_splits (id, expense_id, user_id, amount) VALUES (gen_random_uuid(), $1, $2, $3)
`

type CreateRecurringSplitParams struct {
	ExpenseID uuid.UUID `json:"expense_id"`
	UserID    uuid.UUID `json:"user_id"`
	Amount    int64     `json:"amount"`
}

func (q *Queries) CreateRecurringSplit(ctx context.Context, arg CreateRecurringSplitParams) error {
	_, err := q.db.Exec(ctx, createRecurringSplit, arg.ExpenseID, arg.UserID, arg.Amount)
	return err
}

const createRecurringSplitWithPercentage = `-- name: CreateRecurringSplitWithPercentage :exec
INSERT INTO expense_splits (id, expense_id, user_id, amount, percentage) VALUES (gen_random_uuid(), $1, $2, $3, $4)
`

type CreateRecurringSplitWithPercentageParams struct {
	ExpenseID  uuid.UUID      `json:"expense_id"`
	UserID     uuid.UUID      `json:"user_id"`
	Amount     int64          `json:"amount"`
	Percentage pgtype.Numeric `json:"percentage"`
}

func (q *Queries) CreateRecurringSplitWithPercentage(ctx context.Context, arg CreateRecurringSplitWithPercentageParams) error {
	_, err := q.db.Exec(ctx, createRecurringSplitWithPercentage,
		arg.ExpenseID,
		arg.UserID,
		arg.Amount,
		arg.Percentage,
	)
	return err
}

const createRecurringSplitWithShares = `-- name: CreateRecurringSplitWithShares :exec
INSERT INTO expense_splits (id, expense_id, user_id, shares) VALUES (gen_random_uuid(), $1, $2, $3)
`

type CreateRecurringSplitWithSharesParams struct {
	ExpenseID uuid.UUID   `json:"expense_id"`
	UserID    uuid.UUID   `json:"user_id"`
	Shares    pgtype.Int4 `json:"shares"`
}

func (q *Queries) CreateRecurringSplitWithShares(ctx context.Context, arg CreateRecurringSplitWithSharesParams) error {
	_, err := q.db.Exec(ctx, createRecurringSplitWithShares, arg.ExpenseID, arg.UserID, arg.Shares)
	return err
}

const deleteRecurring = `-- name: DeleteRecurring :execrows
DELETE FROM recurring_expenses
WHERE id = $1 AND group_id IN (SELECT group_id FROM group_members WHERE user_id = $2)
`

type DeleteRecurringParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteRecurring(ctx context.Context, arg DeleteRecurringParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRecurring, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRecurringSplitsSum = `-- name: GetRecurringSplitsSum :one
SELECT coalesce(SUM(amount), 0)::bigint AS sum FROM expense_splits WHERE expense_id = $1
`

func (q *Queries) GetRecurringSplitsSum(ctx context.Context, expenseID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getRecurringSplitsSum, expenseID)
	var sum int64
	err := row.Scan(&sum)
	return sum, err
}

const listRecurringByGroup = `-- name: ListRecurringByGroup :many

SELECT id, description, amount, currency, split_mode, paid_by, frequency, next_run_at, last_run_at, active
FROM recurring_expenses
WHERE group_id = $1
ORDER BY created_at DESC
`

type ListRecurringByGroupRow struct {
	ID          uuid.UUID          `json:"id"`
	Description string             `json:"description"`
	Amount      int64              `json:"amount"`
	Currency    string             `json:"currency"`
	SplitMode   string             `json:"split_mode"`
	PaidBy      uuid.UUID          `json:"paid_by"`
	Frequency   string             `json:"frequency"`
	NextRunAt   pgtype.Timestamptz `json:"next_run_at"`
	LastRunAt   pgtype.Timestamptz `json:"last_run_at"`
	Active      bool               `json:"active"`
}

// Recurring domain queries for sqlc with pgx/v5.
// These replace manual Pool.Query/Exec calls in internal/recurring/handlers.go
// Handler usage: Handler{Pool *pgxpool.Pool, Queries *db.Queries} where Queries wraps the pool.
func (q *Queries) ListRecurringByGroup(ctx context.Context, groupID uuid.UUID) ([]ListRecurringByGroupRow, error) {
	rows, err := q.db.Query(ctx, listRecurringByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecurringByGroupRow
	for rows.Next() {
		var i ListRecurringByGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.SplitMode,
			&i.PaidBy,
			&i.Frequency,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringGroupMembers = `-- name: ListRecurringGroupMembers :many
SELECT user_id FROM group_members WHERE group_id = $1
`

func (q *Queries) ListRecurringGroupMembers(ctx context.Context, groupID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listRecurringGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topUpRecurringSplit = `-- name: TopUpRecurringSplit :exec
UPDATE expense_splits SET amount = amount + $3 WHERE expense_id = $1 AND user_id = $2
`

type TopUpRecurringSplitParams struct {
	ExpenseID uuid.UUID `json:"expense_id"`
	UserID    uuid.UUID `json:"user_id"`
	Amount    int64     `json:"amount"`
}

func (q *Queries) TopUpRecurringSplit(ctx context.Context, arg TopUpRecurringSplitParams) error {
	_, err := q.db.Exec(ctx, topUpRecurringSplit, arg.ExpenseID, arg.UserID, arg.Amount)
	return err
}

const updateRecurringActive = `-- name: UpdateRecurringActive :execrows
UPDATE recurring_expenses SET active = $3, updated_at = now()
WHERE id = $1 AND group_id IN (SELECT group_id FROM group_members WHERE user_id = $2)
`

type UpdateRecurringActiveParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Active bool      `json:"active"`
}

func (q *Queries) UpdateRecurringActive(ctx context.Context, arg UpdateRecurringActiveParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRecurringActive, arg.ID, arg.UserID, arg.Active)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
