// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const searchExpenses = `-- name: SearchExpenses :many
SELECT e.id, e.group_id, e.description, e.amount, e.currency
FROM expenses e
WHERE e.deleted_at IS NULL
  AND e.group_id IN (SELECT group_id FROM group_members WHERE user_id = $1)
  AND (e.description ILIKE '%' || $2 || '%' OR e.notes ILIKE '%' || $2 || '%')
ORDER BY e.created_at DESC
LIMIT 10
`

type SearchExpensesParams struct {
	UserID  uuid.UUID   `json:"user_id"`
	Column2 pgtype.Text `json:"column_2"`
}

type SearchExpensesRow struct {
	ID          uuid.UUID `json:"id"`
	GroupID     uuid.UUID `json:"group_id"`
	Description string    `json:"description"`
	Amount      int64     `json:"amount"`
	Currency    string    `json:"currency"`
}

func (q *Queries) SearchExpenses(ctx context.Context, arg SearchExpensesParams) ([]SearchExpensesRow, error) {
	rows, err := q.db.Query(ctx, searchExpenses, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchExpensesRow
	for rows.Next() {
		var i SearchExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Description,
			&i.Amount,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchGroups = `-- name: SearchGroups :many
SELECT g.id, g.name
FROM groups g
JOIN group_members gm ON gm.group_id = g.id
WHERE gm.user_id = $1
  AND g.archived_at IS NULL
  AND g.name ILIKE '%' || $2 || '%'
LIMIT 10
`

type SearchGroupsParams struct {
	UserID  uuid.UUID   `json:"user_id"`
	Column2 pgtype.Text `json:"column_2"`
}

type SearchGroupsRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) SearchGroups(ctx context.Context, arg SearchGroupsParams) ([]SearchGroupsRow, error) {
	rows, err := q.db.Query(ctx, searchGroups, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchGroupsRow
	for rows.Next() {
		var i SearchGroupsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many

SELECT id, name, coalesce(avatar_url, '') AS avatar_url
FROM users
WHERE is_anonymous = false
  AND (name ILIKE '%' || $1 || '%' OR email ILIKE '%' || $1 || '%')
LIMIT 10
`

type SearchUsersRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	AvatarUrl string    `json:"avatar_url"`
}

// Search domain queries for sqlc with pgx/v5.
// These replace manual Pool.Query/Exec calls in internal/search/handlers.go
// Handler usage: Handler{Pool *pgxpool.Pool, Queries *db.Queries} where Queries wraps the pool.
func (q *Queries) SearchUsers(ctx context.Context, dollar_1 pgtype.Text) ([]SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, searchUsers, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersRow
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(&i.ID, &i.Name, &i.AvatarUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
