// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settlements.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkSettlementIsGroupMember = `-- name: CheckSettlementIsGroupMember :one

SELECT EXISTS(SELECT 1 FROM group_members WHERE group_id = $1 AND user_id = $2) AS is_member
`

type CheckSettlementIsGroupMemberParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

// Settlements domain queries for sqlc with pgx/v5.
// These replace manual Pool.Query/Exec calls in internal/settlements/handlers.go
// Handler usage: Handler{Pool *pgxpool.Pool, Queries *db.Queries} where Queries wraps the pool.
// Transaction usage: qtx := h.Queries.WithTx(tx)
func (q *Queries) CheckSettlementIsGroupMember(ctx context.Context, arg CheckSettlementIsGroupMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkSettlementIsGroupMember, arg.GroupID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const createSettlement = `-- name: CreateSettlement :exec
INSERT INTO settlements (id, group_id, from_user, to_user, amount, currency, note, settled_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateSettlementParams struct {
	ID        uuid.UUID          `json:"id"`
	GroupID   uuid.UUID          `json:"group_id"`
	FromUser  uuid.UUID          `json:"from_user"`
	ToUser    uuid.UUID          `json:"to_user"`
	Amount    int64              `json:"amount"`
	Currency  string             `json:"currency"`
	Note      string             `json:"note"`
	SettledAt pgtype.Timestamptz `json:"settled_at"`
	CreatedBy uuid.UUID          `json:"created_by"`
}

func (q *Queries) CreateSettlement(ctx context.Context, arg CreateSettlementParams) error {
	_, err := q.db.Exec(ctx, createSettlement,
		arg.ID,
		arg.GroupID,
		arg.FromUser,
		arg.ToUser,
		arg.Amount,
		arg.Currency,
		arg.Note,
		arg.SettledAt,
		arg.CreatedBy,
	)
	return err
}

const createSettlementActivity = `-- name: CreateSettlementActivity :exec
INSERT INTO activity_events (group_id, actor_id, type, entity_type, entity_id, payload) VALUES ($1, $2, 'SETTLEMENT_RECORDED', 'settlement', $3, $4)
`

type CreateSettlementActivityParams struct {
	GroupID  uuid.UUID `json:"group_id"`
	ActorID  uuid.UUID `json:"actor_id"`
	EntityID uuid.UUID `json:"entity_id"`
	Payload  []byte    `json:"payload"`
}

func (q *Queries) CreateSettlementActivity(ctx context.Context, arg CreateSettlementActivityParams) error {
	_, err := q.db.Exec(ctx, createSettlementActivity,
		arg.GroupID,
		arg.ActorID,
		arg.EntityID,
		arg.Payload,
	)
	return err
}

const createSettlementNotification = `-- name: CreateSettlementNotification :exec
INSERT INTO notifications (user_id, type, title, body, data) VALUES ($1, 'SETTLEMENT_RECORDED', $2, $3, $4)
`

type CreateSettlementNotificationParams struct {
	UserID uuid.UUID `json:"user_id"`
	Title  string    `json:"title"`
	Body   string    `json:"body"`
	Data   []byte    `json:"data"`
}

func (q *Queries) CreateSettlementNotification(ctx context.Context, arg CreateSettlementNotificationParams) error {
	_, err := q.db.Exec(ctx, createSettlementNotification,
		arg.UserID,
		arg.Title,
		arg.Body,
		arg.Data,
	)
	return err
}

const getSettlementForDelete = `-- name: GetSettlementForDelete :one
SELECT group_id FROM settlements WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSettlementForDelete(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getSettlementForDelete, id)
	var group_id uuid.UUID
	err := row.Scan(&group_id)
	return group_id, err
}

const getSettlementForUpdate = `-- name: GetSettlementForUpdate :one
SELECT group_id, deleted_at FROM settlements WHERE id = $1
`

type GetSettlementForUpdateRow struct {
	GroupID   uuid.UUID          `json:"group_id"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetSettlementForUpdate(ctx context.Context, id uuid.UUID) (GetSettlementForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getSettlementForUpdate, id)
	var i GetSettlementForUpdateRow
	err := row.Scan(&i.GroupID, &i.DeletedAt)
	return i, err
}

const getSettlementGroupCurrency = `-- name: GetSettlementGroupCurrency :one
SELECT currency FROM groups WHERE id = $1
`

func (q *Queries) GetSettlementGroupCurrency(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getSettlementGroupCurrency, id)
	var currency string
	err := row.Scan(&currency)
	return currency, err
}

const listSettlements = `-- name: ListSettlements :many
SELECT id, from_user, to_user, amount, currency, note, settled_at, created_by, created_at
FROM settlements
WHERE group_id = $1 AND deleted_at IS NULL
ORDER BY settled_at DESC, created_at DESC
LIMIT $2
`

type ListSettlementsParams struct {
	GroupID uuid.UUID `json:"group_id"`
	Limit   int32     `json:"limit"`
}

type ListSettlementsRow struct {
	ID        uuid.UUID          `json:"id"`
	FromUser  uuid.UUID          `json:"from_user"`
	ToUser    uuid.UUID          `json:"to_user"`
	Amount    int64              `json:"amount"`
	Currency  string             `json:"currency"`
	Note      string             `json:"note"`
	SettledAt pgtype.Timestamptz `json:"settled_at"`
	CreatedBy uuid.UUID          `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListSettlements(ctx context.Context, arg ListSettlementsParams) ([]ListSettlementsRow, error) {
	rows, err := q.db.Query(ctx, listSettlements, arg.GroupID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSettlementsRow
	for rows.Next() {
		var i ListSettlementsRow
		if err := rows.Scan(
			&i.ID,
			&i.FromUser,
			&i.ToUser,
			&i.Amount,
			&i.Currency,
			&i.Note,
			&i.SettledAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteSettlement = `-- name: SoftDeleteSettlement :exec
UPDATE settlements SET deleted_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteSettlement(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteSettlement, id)
	return err
}

const updateSettlementAmount = `-- name: UpdateSettlementAmount :exec
UPDATE settlements SET amount = $1, updated_at = now() WHERE id = $2
`

type UpdateSettlementAmountParams struct {
	Amount int64     `json:"amount"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdateSettlementAmount(ctx context.Context, arg UpdateSettlementAmountParams) error {
	_, err := q.db.Exec(ctx, updateSettlementAmount, arg.Amount, arg.ID)
	return err
}

const updateSettlementNote = `-- name: UpdateSettlementNote :exec
UPDATE settlements SET note = $1, updated_at = now() WHERE id = $2
`

type UpdateSettlementNoteParams struct {
	Note string    `json:"note"`
	ID   uuid.UUID `json:"id"`
}

func (q *Queries) UpdateSettlementNote(ctx context.Context, arg UpdateSettlementNoteParams) error {
	_, err := q.db.Exec(ctx, updateSettlementNote, arg.Note, arg.ID)
	return err
}
