// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getGroupStatsTotal = `-- name: GetGroupStatsTotal :one

SELECT coalesce(SUM(amount * COALESCE(exchange_rate, 1)), 0)::bigint AS total,
       coalesce(ROUND(AVG(amount * COALESCE(exchange_rate, 1))), 0)::bigint AS avg,
       COUNT(*)::bigint AS count
FROM expenses
WHERE group_id = $1 AND deleted_at IS NULL
`

type GetGroupStatsTotalRow struct {
	Total int64 `json:"total"`
	Avg   int64 `json:"avg"`
	Count int64 `json:"count"`
}

// Stats domain queries for sqlc with pgx/v5.
// These replace manual Pool.Query/Exec calls in internal/stats/handlers.go
// Handler usage: Handler{Pool *pgxpool.Pool, Queries *db.Queries} where Queries wraps the pool.
func (q *Queries) GetGroupStatsTotal(ctx context.Context, groupID uuid.UUID) (GetGroupStatsTotalRow, error) {
	row := q.db.QueryRow(ctx, getGroupStatsTotal, groupID)
	var i GetGroupStatsTotalRow
	err := row.Scan(&i.Total, &i.Avg, &i.Count)
	return i, err
}

const getGroupStatsTotalLast30 = `-- name: GetGroupStatsTotalLast30 :one
SELECT coalesce(SUM(amount * COALESCE(exchange_rate, 1)), 0)::bigint AS total,
       coalesce(ROUND(AVG(amount * COALESCE(exchange_rate, 1))), 0)::bigint AS avg,
       COUNT(*)::bigint AS count
FROM expenses
WHERE group_id = $1 AND deleted_at IS NULL AND expense_date >= CURRENT_DATE - interval '30 days'
`

type GetGroupStatsTotalLast30Row struct {
	Total int64 `json:"total"`
	Avg   int64 `json:"avg"`
	Count int64 `json:"count"`
}

func (q *Queries) GetGroupStatsTotalLast30(ctx context.Context, groupID uuid.UUID) (GetGroupStatsTotalLast30Row, error) {
	row := q.db.QueryRow(ctx, getGroupStatsTotalLast30, groupID)
	var i GetGroupStatsTotalLast30Row
	err := row.Scan(&i.Total, &i.Avg, &i.Count)
	return i, err
}

const getGroupStatsTotalThisMonth = `-- name: GetGroupStatsTotalThisMonth :one
SELECT coalesce(SUM(amount * COALESCE(exchange_rate, 1)), 0)::bigint AS total,
       coalesce(ROUND(AVG(amount * COALESCE(exchange_rate, 1))), 0)::bigint AS avg,
       COUNT(*)::bigint AS count
FROM expenses
WHERE group_id = $1 AND deleted_at IS NULL AND expense_date >= date_trunc('month', CURRENT_DATE)
`

type GetGroupStatsTotalThisMonthRow struct {
	Total int64 `json:"total"`
	Avg   int64 `json:"avg"`
	Count int64 `json:"count"`
}

func (q *Queries) GetGroupStatsTotalThisMonth(ctx context.Context, groupID uuid.UUID) (GetGroupStatsTotalThisMonthRow, error) {
	row := q.db.QueryRow(ctx, getGroupStatsTotalThisMonth, groupID)
	var i GetGroupStatsTotalThisMonthRow
	err := row.Scan(&i.Total, &i.Avg, &i.Count)
	return i, err
}

const getGroupStatsTotalThisYear = `-- name: GetGroupStatsTotalThisYear :one
SELECT coalesce(SUM(amount * COALESCE(exchange_rate, 1)), 0)::bigint AS total,
       coalesce(ROUND(AVG(amount * COALESCE(exchange_rate, 1))), 0)::bigint AS avg,
       COUNT(*)::bigint AS count
FROM expenses
WHERE group_id = $1 AND deleted_at IS NULL AND expense_date >= date_trunc('year', CURRENT_DATE)
`

type GetGroupStatsTotalThisYearRow struct {
	Total int64 `json:"total"`
	Avg   int64 `json:"avg"`
	Count int64 `json:"count"`
}

func (q *Queries) GetGroupStatsTotalThisYear(ctx context.Context, groupID uuid.UUID) (GetGroupStatsTotalThisYearRow, error) {
	row := q.db.QueryRow(ctx, getGroupStatsTotalThisYear, groupID)
	var i GetGroupStatsTotalThisYearRow
	err := row.Scan(&i.Total, &i.Avg, &i.Count)
	return i, err
}

const getStatsByCategory = `-- name: GetStatsByCategory :many
SELECT c.name, coalesce(c.icon, 'tag') AS icon, coalesce(SUM(ROUND(e.amount * COALESCE(e.exchange_rate, 1))::bigint), 0)::bigint AS total, COUNT(*)::bigint AS count
FROM expenses e
LEFT JOIN categories c ON c.id = e.category_id
WHERE e.group_id = $1 AND e.deleted_at IS NULL
GROUP BY c.name, c.icon
ORDER BY total DESC
`

type GetStatsByCategoryRow struct {
	Name  pgtype.Text `json:"name"`
	Icon  string      `json:"icon"`
	Total int64       `json:"total"`
	Count int64       `json:"count"`
}

func (q *Queries) GetStatsByCategory(ctx context.Context, groupID uuid.UUID) ([]GetStatsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getStatsByCategory, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStatsByCategoryRow
	for rows.Next() {
		var i GetStatsByCategoryRow
		if err := rows.Scan(
			&i.Name,
			&i.Icon,
			&i.Total,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatsByCategoryLast30 = `-- name: GetStatsByCategoryLast30 :many
SELECT c.name, coalesce(c.icon, 'tag') AS icon, coalesce(SUM(ROUND(e.amount * COALESCE(e.exchange_rate, 1))::bigint), 0)::bigint AS total, COUNT(*)::bigint AS count
FROM expenses e
LEFT JOIN categories c ON c.id = e.category_id
WHERE e.group_id = $1 AND e.deleted_at IS NULL AND e.expense_date >= CURRENT_DATE - interval '30 days'
GROUP BY c.name, c.icon
ORDER BY total DESC
`

type GetStatsByCategoryLast30Row struct {
	Name  pgtype.Text `json:"name"`
	Icon  string      `json:"icon"`
	Total int64       `json:"total"`
	Count int64       `json:"count"`
}

func (q *Queries) GetStatsByCategoryLast30(ctx context.Context, groupID uuid.UUID) ([]GetStatsByCategoryLast30Row, error) {
	rows, err := q.db.Query(ctx, getStatsByCategoryLast30, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStatsByCategoryLast30Row
	for rows.Next() {
		var i GetStatsByCategoryLast30Row
		if err := rows.Scan(
			&i.Name,
			&i.Icon,
			&i.Total,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatsByCategoryThisMonth = `-- name: GetStatsByCategoryThisMonth :many
SELECT c.name, coalesce(c.icon, 'tag') AS icon, coalesce(SUM(ROUND(e.amount * COALESCE(e.exchange_rate, 1))::bigint), 0)::bigint AS total, COUNT(*)::bigint AS count
FROM expenses e
LEFT JOIN categories c ON c.id = e.category_id
WHERE e.group_id = $1 AND e.deleted_at IS NULL AND e.expense_date >= date_trunc('month', CURRENT_DATE)
GROUP BY c.name, c.icon
ORDER BY total DESC
`

type GetStatsByCategoryThisMonthRow struct {
	Name  pgtype.Text `json:"name"`
	Icon  string      `json:"icon"`
	Total int64       `json:"total"`
	Count int64       `json:"count"`
}

func (q *Queries) GetStatsByCategoryThisMonth(ctx context.Context, groupID uuid.UUID) ([]GetStatsByCategoryThisMonthRow, error) {
	rows, err := q.db.Query(ctx, getStatsByCategoryThisMonth, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStatsByCategoryThisMonthRow
	for rows.Next() {
		var i GetStatsByCategoryThisMonthRow
		if err := rows.Scan(
			&i.Name,
			&i.Icon,
			&i.Total,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatsByCategoryThisYear = `-- name: GetStatsByCategoryThisYear :many
SELECT c.name, coalesce(c.icon, 'tag') AS icon, coalesce(SUM(ROUND(e.amount * COALESCE(e.exchange_rate, 1))::bigint), 0)::bigint AS total, COUNT(*)::bigint AS count
FROM expenses e
LEFT JOIN categories c ON c.id = e.category_id
WHERE e.group_id = $1 AND e.deleted_at IS NULL AND e.expense_date >= date_trunc('year', CURRENT_DATE)
GROUP BY c.name, c.icon
ORDER BY total DESC
`

type GetStatsByCategoryThisYearRow struct {
	Name  pgtype.Text `json:"name"`
	Icon  string      `json:"icon"`
	Total int64       `json:"total"`
	Count int64       `json:"count"`
}

func (q *Queries) GetStatsByCategoryThisYear(ctx context.Context, groupID uuid.UUID) ([]GetStatsByCategoryThisYearRow, error) {
	rows, err := q.db.Query(ctx, getStatsByCategoryThisYear, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStatsByCategoryThisYearRow
	for rows.Next() {
		var i GetStatsByCategoryThisYearRow
		if err := rows.Scan(
			&i.Name,
			&i.Icon,
			&i.Total,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatsByMember = `-- name: GetStatsByMember :many
SELECT u.id, u.name, coalesce(SUM(ROUND(e.amount * COALESCE(e.exchange_rate, 1))::bigint), 0)::bigint AS total, COUNT(e.id)::bigint AS count
FROM users u
LEFT JOIN expenses e ON e.paid_by = u.id AND e.group_id = $1 AND e.deleted_at IS NULL
WHERE u.id IN (SELECT user_id FROM group_members WHERE group_id = $1)
GROUP BY u.id, u.name
`

type GetStatsByMemberRow struct {
	ID    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	Total int64     `json:"total"`
	Count int64     `json:"count"`
}

func (q *Queries) GetStatsByMember(ctx context.Context, groupID uuid.UUID) ([]GetStatsByMemberRow, error) {
	rows, err := q.db.Query(ctx, getStatsByMember, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStatsByMemberRow
	for rows.Next() {
		var i GetStatsByMemberRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Total,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatsMonthly = `-- name: GetStatsMonthly :many
SELECT to_char(expense_date, 'YYYY-MM') AS month, SUM(ROUND(amount * COALESCE(exchange_rate, 1))::bigint)::bigint AS total
FROM expenses
WHERE group_id = $1 AND deleted_at IS NULL
GROUP BY month
ORDER BY month
`

type GetStatsMonthlyRow struct {
	Month string `json:"month"`
	Total int64  `json:"total"`
}

func (q *Queries) GetStatsMonthly(ctx context.Context, groupID uuid.UUID) ([]GetStatsMonthlyRow, error) {
	rows, err := q.db.Query(ctx, getStatsMonthly, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStatsMonthlyRow
	for rows.Next() {
		var i GetStatsMonthlyRow
		if err := rows.Scan(&i.Month, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatsMonthlyLast30 = `-- name: GetStatsMonthlyLast30 :many
SELECT to_char(expense_date, 'YYYY-MM') AS month, SUM(ROUND(amount * COALESCE(exchange_rate, 1))::bigint)::bigint AS total
FROM expenses
WHERE group_id = $1 AND deleted_at IS NULL AND expense_date >= CURRENT_DATE - interval '30 days'
GROUP BY month
ORDER BY month
`

type GetStatsMonthlyLast30Row struct {
	Month string `json:"month"`
	Total int64  `json:"total"`
}

func (q *Queries) GetStatsMonthlyLast30(ctx context.Context, groupID uuid.UUID) ([]GetStatsMonthlyLast30Row, error) {
	rows, err := q.db.Query(ctx, getStatsMonthlyLast30, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStatsMonthlyLast30Row
	for rows.Next() {
		var i GetStatsMonthlyLast30Row
		if err := rows.Scan(&i.Month, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatsMonthlyThisMonth = `-- name: GetStatsMonthlyThisMonth :many
SELECT to_char(expense_date, 'YYYY-MM') AS month, SUM(ROUND(amount * COALESCE(exchange_rate, 1))::bigint)::bigint AS total
FROM expenses
WHERE group_id = $1 AND deleted_at IS NULL AND expense_date >= date_trunc('month', CURRENT_DATE)
GROUP BY month
ORDER BY month
`

type GetStatsMonthlyThisMonthRow struct {
	Month string `json:"month"`
	Total int64  `json:"total"`
}

func (q *Queries) GetStatsMonthlyThisMonth(ctx context.Context, groupID uuid.UUID) ([]GetStatsMonthlyThisMonthRow, error) {
	rows, err := q.db.Query(ctx, getStatsMonthlyThisMonth, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStatsMonthlyThisMonthRow
	for rows.Next() {
		var i GetStatsMonthlyThisMonthRow
		if err := rows.Scan(&i.Month, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatsMonthlyThisYear = `-- name: GetStatsMonthlyThisYear :many
SELECT to_char(expense_date, 'YYYY-MM') AS month, SUM(ROUND(amount * COALESCE(exchange_rate, 1))::bigint)::bigint AS total
FROM expenses
WHERE group_id = $1 AND deleted_at IS NULL AND expense_date >= date_trunc('year', CURRENT_DATE)
GROUP BY month
ORDER BY month
`

type GetStatsMonthlyThisYearRow struct {
	Month string `json:"month"`
	Total int64  `json:"total"`
}

func (q *Queries) GetStatsMonthlyThisYear(ctx context.Context, groupID uuid.UUID) ([]GetStatsMonthlyThisYearRow, error) {
	rows, err := q.db.Query(ctx, getStatsMonthlyThisYear, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStatsMonthlyThisYearRow
	for rows.Next() {
		var i GetStatsMonthlyThisYearRow
		if err := rows.Scan(&i.Month, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
