// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkFriendshipAccepted = `-- name: CheckFriendshipAccepted :one
SELECT EXISTS(
    SELECT 1 FROM friendships
    WHERE ((user_id = $1 AND friend_id = $2) OR (user_id = $2 AND friend_id = $1))
      AND status = 'ACCEPTED'
) AS is_friend
`

type CheckFriendshipAcceptedParams struct {
	UserID   uuid.UUID `json:"user_id"`
	FriendID uuid.UUID `json:"friend_id"`
}

func (q *Queries) CheckFriendshipAccepted(ctx context.Context, arg CheckFriendshipAcceptedParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkFriendshipAccepted, arg.UserID, arg.FriendID)
	var is_friend bool
	err := row.Scan(&is_friend)
	return is_friend, err
}

const getMe = `-- name: GetMe :one
SELECT name, email, coalesce(avatar_url, '') AS avatar_url, default_currency, timezone, email_verified_at, password_hash IS NOT NULL AS has_password
FROM users WHERE id = $1
`

type GetMeRow struct {
	Name            string             `json:"name"`
	Email           string             `json:"email"`
	AvatarUrl       string             `json:"avatar_url"`
	DefaultCurrency string             `json:"default_currency"`
	Timezone        string             `json:"timezone"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	HasPassword     interface{}        `json:"has_password"`
}

func (q *Queries) GetMe(ctx context.Context, id uuid.UUID) (GetMeRow, error) {
	row := q.db.QueryRow(ctx, getMe, id)
	var i GetMeRow
	err := row.Scan(
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.DefaultCurrency,
		&i.Timezone,
		&i.EmailVerifiedAt,
		&i.HasPassword,
	)
	return i, err
}

const getUserByIDForMe = `-- name: GetUserByIDForMe :one
SELECT name, email, coalesce(avatar_url, '') AS avatar_url, default_currency, timezone, email_verified_at::text AS email_verified_at_text, password_hash IS NOT NULL AS has_password FROM users WHERE id = $1
`

type GetUserByIDForMeRow struct {
	Name                string      `json:"name"`
	Email               string      `json:"email"`
	AvatarUrl           string      `json:"avatar_url"`
	DefaultCurrency     string      `json:"default_currency"`
	Timezone            string      `json:"timezone"`
	EmailVerifiedAtText string      `json:"email_verified_at_text"`
	HasPassword         interface{} `json:"has_password"`
}

func (q *Queries) GetUserByIDForMe(ctx context.Context, id uuid.UUID) (GetUserByIDForMeRow, error) {
	row := q.db.QueryRow(ctx, getUserByIDForMe, id)
	var i GetUserByIDForMeRow
	err := row.Scan(
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.DefaultCurrency,
		&i.Timezone,
		&i.EmailVerifiedAtText,
		&i.HasPassword,
	)
	return i, err
}

const getUserPasswordHash = `-- name: GetUserPasswordHash :one
SELECT password_hash FROM users WHERE id = $1
`

func (q *Queries) GetUserPasswordHash(ctx context.Context, id uuid.UUID) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getUserPasswordHash, id)
	var password_hash pgtype.Text
	err := row.Scan(&password_hash)
	return password_hash, err
}

const getUserPaymentInfo = `-- name: GetUserPaymentInfo :one

SELECT coalesce(bank_qr_url, '') AS bank_qr_url, coalesce(bank_name, '') AS bank_name, coalesce(payment_handle, '') AS payment_handle
FROM users WHERE id = $1
`

type GetUserPaymentInfoRow struct {
	BankQrUrl     string `json:"bank_qr_url"`
	BankName      string `json:"bank_name"`
	PaymentHandle string `json:"payment_handle"`
}

// Users domain queries for sqlc with pgx/v5.
// These replace manual Pool.Query/Exec calls in internal/users/handlers.go
// Handler usage: Handler{Pool *pgxpool.Pool, Queries *db.Queries} where Queries wraps the pool.
func (q *Queries) GetUserPaymentInfo(ctx context.Context, id uuid.UUID) (GetUserPaymentInfoRow, error) {
	row := q.db.QueryRow(ctx, getUserPaymentInfo, id)
	var i GetUserPaymentInfoRow
	err := row.Scan(&i.BankQrUrl, &i.BankName, &i.PaymentHandle)
	return i, err
}

const getUserPaymentInfoForFriend = `-- name: GetUserPaymentInfoForFriend :one
SELECT coalesce(bank_qr_url, '') AS bank_qr_url, coalesce(bank_name, '') AS bank_name, coalesce(payment_handle, '') AS payment_handle
FROM users WHERE id = $1 AND is_anonymous = false
`

type GetUserPaymentInfoForFriendRow struct {
	BankQrUrl     string `json:"bank_qr_url"`
	BankName      string `json:"bank_name"`
	PaymentHandle string `json:"payment_handle"`
}

func (q *Queries) GetUserPaymentInfoForFriend(ctx context.Context, id uuid.UUID) (GetUserPaymentInfoForFriendRow, error) {
	row := q.db.QueryRow(ctx, getUserPaymentInfoForFriend, id)
	var i GetUserPaymentInfoForFriendRow
	err := row.Scan(&i.BankQrUrl, &i.BankName, &i.PaymentHandle)
	return i, err
}

const getUserPublic = `-- name: GetUserPublic :one
SELECT name, coalesce(avatar_url, '') AS avatar_url FROM users WHERE id = $1 AND is_anonymous = false
`

type GetUserPublicRow struct {
	Name      string `json:"name"`
	AvatarUrl string `json:"avatar_url"`
}

func (q *Queries) GetUserPublic(ctx context.Context, id uuid.UUID) (GetUserPublicRow, error) {
	row := q.db.QueryRow(ctx, getUserPublic, id)
	var i GetUserPublicRow
	err := row.Scan(&i.Name, &i.AvatarUrl)
	return i, err
}

const searchUsersByName = `-- name: SearchUsersByName :many
SELECT u.id, u.name, u.email, coalesce(u.avatar_url, '') AS avatar_url,
       EXISTS (
           SELECT 1 FROM friendships f
           WHERE f.user_id = LEAST($2::uuid, u.id) AND f.friend_id = GREATEST($2::uuid, u.id)
             AND f.status = 'PENDING' AND f.action_by = $2
       ) AS requested
FROM users u
WHERE u.id <> $2
  AND u.is_anonymous = false
  AND (u.name ILIKE '%' || $1 || '%' OR u.email ILIKE '%' || $1 || '%')
ORDER BY u.name
LIMIT 20
`

type SearchUsersByNameParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Column2 pgtype.UUID `json:"column_2"`
}

type SearchUsersByNameRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	AvatarUrl string    `json:"avatar_url"`
	Requested bool      `json:"requested"`
}

func (q *Queries) SearchUsersByName(ctx context.Context, arg SearchUsersByNameParams) ([]SearchUsersByNameRow, error) {
	rows, err := q.db.Query(ctx, searchUsersByName, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersByNameRow
	for rows.Next() {
		var i SearchUsersByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.AvatarUrl,
			&i.Requested,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users SET name = 'Deleted User', email = $1, password_hash = 'deleted', avatar_url = NULL, is_anonymous = true, updated_at = now() WHERE id = $2
`

type SoftDeleteUserParams struct {
	Email string    `json:"email"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) error {
	_, err := q.db.Exec(ctx, softDeleteUser, arg.Email, arg.ID)
	return err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :exec
UPDATE users SET avatar_url = $1, updated_at = now() WHERE id = $2
`

type UpdateUserAvatarParams struct {
	AvatarUrl pgtype.Text `json:"avatar_url"`
	ID        uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error {
	_, err := q.db.Exec(ctx, updateUserAvatar, arg.AvatarUrl, arg.ID)
	return err
}

const updateUserDefaultCurrency = `-- name: UpdateUserDefaultCurrency :exec
UPDATE users SET default_currency = $1, updated_at = now() WHERE id = $2
`

type UpdateUserDefaultCurrencyParams struct {
	DefaultCurrency string    `json:"default_currency"`
	ID              uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserDefaultCurrency(ctx context.Context, arg UpdateUserDefaultCurrencyParams) error {
	_, err := q.db.Exec(ctx, updateUserDefaultCurrency, arg.DefaultCurrency, arg.ID)
	return err
}

const updateUserEmail = `-- name: UpdateUserEmail :exec
UPDATE users SET email = $1, updated_at = now(), email_verified_at = NULL WHERE id = $2
`

type UpdateUserEmailParams struct {
	Email string    `json:"email"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error {
	_, err := q.db.Exec(ctx, updateUserEmail, arg.Email, arg.ID)
	return err
}

const updateUserName = `-- name: UpdateUserName :exec
UPDATE users SET name = $1, updated_at = now() WHERE id = $2
`

type UpdateUserNameParams struct {
	Name string    `json:"name"`
	ID   uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) error {
	_, err := q.db.Exec(ctx, updateUserName, arg.Name, arg.ID)
	return err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :exec
UPDATE users SET password_hash = $1, updated_at = now() WHERE id = $2
`

type UpdateUserPasswordHashParams struct {
	PasswordHash pgtype.Text `json:"password_hash"`
	ID           uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordHash, arg.PasswordHash, arg.ID)
	return err
}

const updateUserPaymentInfo = `-- name: UpdateUserPaymentInfo :exec
UPDATE users SET bank_qr_url = $1, bank_name = $2, payment_handle = $3, updated_at = now() WHERE id = $4
`

type UpdateUserPaymentInfoParams struct {
	BankQrUrl     pgtype.Text `json:"bank_qr_url"`
	BankName      pgtype.Text `json:"bank_name"`
	PaymentHandle pgtype.Text `json:"payment_handle"`
	ID            uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateUserPaymentInfo(ctx context.Context, arg UpdateUserPaymentInfoParams) error {
	_, err := q.db.Exec(ctx, updateUserPaymentInfo,
		arg.BankQrUrl,
		arg.BankName,
		arg.PaymentHandle,
		arg.ID,
	)
	return err
}

const updateUserTimezone = `-- name: UpdateUserTimezone :exec
UPDATE users SET timezone = $1, updated_at = now() WHERE id = $2
`

type UpdateUserTimezoneParams struct {
	Timezone string    `json:"timezone"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserTimezone(ctx context.Context, arg UpdateUserTimezoneParams) error {
	_, err := q.db.Exec(ctx, updateUserTimezone, arg.Timezone, arg.ID)
	return err
}
